### ISSUE TITLE
Allow "none" as an option for attributeSeparator

### ISSUE THREAD

**Issue by jubairsaidi** [prettier/plugin-pug#102]
## Request / Idea

pug does not require commas following the attribute definitions, so can we add one more setting option to `attributeSeparator` so it can be `always || as-needed || none` ?

## Input

```pug
container(
  someAttribute="value",
  another="OtherValue"
)
```

## Expected Output

```pug
container(
  someAttribute="value"
  another="OtherValue"
)

```

**Comment by Shinigami92** [comment]
`'none'` is the equivalent of `'as-needed'`!
Something like `'none'` can potentially BREAK your syntax ⚠️ 

e.g.:

```pug
div(
  class="test"
  :style="'color: red'"         // <- this line has a `:` and can break your code/syntax
)
```

**Comment by jubairsaidi** [comment]
> `'none'` is the equivalent of `'as-needed'`!
> Something like `'none'` can potentially BREAK your syntax ⚠️
> 
> e.g.:
> 
> ```
> div(
>   class="test"
>   :style="'color: red'"         // <- this line has a `:` and can break your code/syntax
> )
> ```

that just looks like something that shouldn't be done lol but I kind of surprised that breaks your code... what frameworks does that break?  it doesn't in vue template="pug"

**Comment by Shinigami92** [comment]
Sorry for my rush comment yesterday :)

You can read some parts here #13

I tried following in [pughtml](https://pughtml.com) (cause I use `vue` myself)
```pug
div(
  class="test"
  :bind="'bind'"
  :bind2="'bind2'"
  @click="click()"
  @click2="click2()"
)
```

Maybe the [update](https://github.com/prettier/plugin-pug/commit/b644b044a47265d4b4bd2392793048d35505913a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) `pug-lexer` from v4 to v5 made it more safe 🤔 

Or maybe it always was only an angular problem 🤷‍♂️

I remember that pug-lint also complains about such problems
Need to rewatch this at work with my huge code base so I can test it in real world

Aside that, feel free to start with a PR
Should be simple, cause it's only a third option

https://github.com/prettier/plugin-pug/blob/4795af50632c7c7b0d7c137b7a70222207a52a3a/src/options/index.ts#L3

If you need any help, feel free to ask and I can also start writing a `CONTRIBUTING.md`

**Comment by Shinigami92** [comment]
At least for the Vue syntax, something has apparently changed at some point 🤷‍♂️

**Comment by jubairsaidi** [comment]
sounds good! sorry for the late response, it's been a busy couple weeks :) I'll see about posting a PR sometime next week.  Thanks!

**Comment by lehni** [comment]
We've been using attributes with `:` as the `v-bind` short-hand in Vue single component files without any attribute separators in a large project for over two years, and not once was there a problem with that syntax. I'd be great to have the `none` option!

**Comment by lehni** [comment]
Thank yuo @Shinigami92 for the help with my PRs and the swift merge and release!
