### ISSUE TITLE
New rule names of aliases for prettier defaults

### ISSUE THREAD

**Issue by SkyaTura** [prettier/plugin-pug#105]
## Request / Idea
Use new names or aliases for rules that are specific for Pug instead of using default ones.

## Current Configuration

```json
{
  "bracketSpacing": true,
  "overrides": [
    {
      "files": "*.pug",
      "options": {
        "parser": "pug",
        "bracketSpacing": false
      }
    }
  ]
}
```

## Expected Configuration

```json
{
  "bracketSpacing": true,
  "pugBracketSpacing": false
}
```

## Additional Context

Using files override won't work in mixed files, like Vue's Single File Components since it doesn't recognizes Pug templates as a file.

**Comment by Shinigami92** [comment]
The reason/context is really helpful
I will look into this the next few days
