### ISSUE TITLE
Mixins and Includes

### ISSUE THREAD

**Issue by marlonmarcello** [prettier/plugin-pug#11]
Hi there!
I am having an a weird issue with mixins and includes.
I am using the default settings.

The testing file:
```
doctype html

include ./includes/_helpers.pug

html
  head
    title Test
  body
    +stylesheet('test')
```

### Issue 1
`include`s are turning into tags, like this:
`include./includes/_helpers.pug`

### Issue 2
An error is returned for the `+stylesheet()` mixin.
```
[error] test.pug: Error: Unhandled token: {"type":"call","loc":{"start":{"line":9,"column":5},"end":{"line":9,"column":24}},"val":"stylesheet","args":"'test'"}
[error]     at Object.print (/Volumes/projects/production/node_modules/@prettier/plugin-pug/dist/index.js:461:35)
[error]     at callPluginPrintFunction (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:13622:18)
[error]     at /Volumes/projects/production/node_modules/prettier/bin-prettier.js:13573:16
[error]     at Object.printComments (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:13295:17)
[error]     at printGenerically (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:13572:22)
[error]     at printAstToDoc (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:13584:16)
[error]     at coreFormat (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:13903:16)
[error]     at format (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:14148:73)
[error]     at formatWithCursor (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:14164:12)
[error]     at Object.formatWithCursor (/Volumes/projects/production/node_modules/prettier/bin-prettier.js:42758:15)
```

**Comment by Shinigami92** [comment]
Thanks, absolutely no problem
I did not handle every token because I did not know pug three months ago
I will be implementing this token in the near future

**Comment by marlonmarcello** [comment]
Awesome man, thanks a ton @Shinigami92 !

**Comment by Shinigami92** [comment]
@marlonmarcello Thank YOU for supporting me, giving feedback and using my work 😃

**Comment by Shinigami92** [comment]
@marlonmarcello Released: https://www.npmjs.com/package/@prettier/plugin-pug/v/1.0.0-alpha.9

**Comment by marlonmarcello** [comment]
That was fast! ⚡️⚡️⚡️
Gonna try now.

**Comment by marlonmarcello** [comment]
Working like a charm! 🥇 
I got another question for ya, I noticed that commas are getting added to the attributes so for example:
`a(href="//google.com" target="_blank")`
becomes
`a(href="//google.com", target="_blank")`

I don't see any reference to this on the docs: https://pugjs.org/language/attributes.html
Do you plan on having that as an option later on or is it gonna be permanent?

**Comment by Shinigami92** [comment]
Cool that it works

Yes, that was planned for later

Can you please make a porposal / feature request with an option that should be taken?
