### ISSUE TITLE
Bug: The indentations of objects in class attributes are broken

### ISSUE THREAD

**Issue by yuheiy** [prettier/plugin-pug#110]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.5.1        |
| Prettier | v2.1.2        |
| Node     | v12.18.4        |
| OS       | mac |

## Input

```pug
div
  div(class={
    a: true,
    b: false,
  })
```

## Output or Error

```bash
div
  div(class={
  a: true,
  b: false,
})
```

## Expected Output

```pug
div
  div(class={
    a: true,
    b: false,
  })
```

**Comment by Shinigami92** [comment]
Will be in next release
Together with another feature
