### ISSUE TITLE
Bug: The indentations of objects with long lines in multiline class attributes are broken

### ISSUE THREAD

**Issue by yuheiy** [prettier/plugin-pug#112]
Thank you for resolving #110. But the formatting in my code is still broken.

## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.6.0        |
| Prettier | v2.1.2        |
| Node     | v12.18.4        |
| OS       | mac |

## Input

```pug
div(
  class={
    aaaaaaaaaaaaaaaaaaaaaaaaaaaa: true,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbb: false,
  }
)
```

## Output or Error

```pug
div(
  class={
  aaaaaaaaaaaaaaaaaaaaaaaaaaaa: true,
  bbbbbbbbbbbbbbbbbbbbbbbbbbbb: false,
}
)
```

## Expected Output

```pug
div(
  class={
    aaaaaaaaaaaaaaaaaaaaaaaaaaaa: true,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbb: false,
  }
)
```

**Comment by Shinigami92** [comment]
How is this even possible? .-.

Need to check this, but did you made a clean install after updating? (removing `node_modules`)

**Comment by yuheiy** [comment]
Yes. I'm using 1.6.0.

**Comment by Shinigami92** [comment]
oof... I know why... will try to fix it sometime today

**Comment by Shinigami92** [comment]
solved in https://github.com/prettier/plugin-pug/commit/5a6082ca126c292673779bc02817390b526b9a97
