### ISSUE TITLE
Bug: Incorrect indenting of same level lines

### ISSUE THREAD

**Issue by SkyaTura** [prettier/plugin-pug#114]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.6.1        |
| Prettier | v2.1.1        |
| Node     | v10.16.3        |
| OS       | mac |

## Input

```pug
  div
  div
  div
```

## Output or Error

```pug
div
  div
  div
```

## Expected Output

```pug
div
div
div
```

## Additional Context

I think it is self explained by the examples why this is an error.

**Comment by Shinigami92** [comment]
Will look into it, but don't know if I will fix this if this is hard to fix, cause you can easily workaround that by manually check the indentation

**Comment by Shinigami92** [comment]
I'm getting this token stream:

```json
[
  { "type": "tag",     "loc": { "start": { "line": 1, "column": 1 }, "end": { "line": 1, "column": 4 } }, "val": "div" },
  { "type": "indent",  "loc": { "start": { "line": 2, "column": 1 }, "end": { "line": 2, "column": 3 } }, "val": 2     },
  { "type": "tag",     "loc": { "start": { "line": 2, "column": 3 }, "end": { "line": 2, "column": 6 } }, "val": "div" },
  { "type": "newline", "loc": { "start": { "line": 3, "column": 1 }, "end": { "line": 3, "column": 3 } }               },
  { "type": "tag",     "loc": { "start": { "line": 3, "column": 3 }, "end": { "line": 3, "column": 6 } }, "val": "div" },
  { "type": "outdent", "loc": { "start": { "line": 4, "column": 1 }, "end": { "line": 4, "column": 1 } }               },
  { "type": "eos",     "loc": { "start": { "line": 4, "column": 1 }, "end": { "line": 4, "column": 1 } }               }
]
```

So as you can see, it is technically a problem of pug itself :slightly_frowning_face:  
If you want you can try to fix that, but I don't think is will help much and just add much complexity to the processing...
So if you are satisfied with just handling this manually and remove these indents by yourself (e.g. using IDEs multicurser functionality), I vote for labeling this issue as `wontfix`

**Comment by SkyaTura** [comment]
How about adding wontfix and a note on documentation? To warn people when they choose to implement this on already existing codebases.

**Comment by Shinigami92** [comment]
That I can definitely do!

**Comment by Shinigami92** [comment]
https://github.com/prettier/plugin-pug/commit/72f2bee793c67fc063568771427f43342d1aa22d
