### ISSUE TITLE
Option to control threshold of amount of attributes to be put on separate lines

### ISSUE THREAD

**Issue by lehni** [prettier/plugin-pug#118]
## Request / Idea

It would be nice if there was an option with which I could set a threshold of the amount of attributes that should always be put on separate lines, regardless of wether they fit into `printWidth` chars or not, .e.g.

```js
attributesOnNewLineThreshold: 2
```

## Input

```pug
.container-with-one-attribute(attribute1='foo')

.container-with-two-attributes(attribute1='foo' attribute2='bar')
```

## Expected Output

```pug
.container-with-one-attribute(attribute1='foo')

.container-with-two-attributes(
  attribute1='foo'
  attribute2='bar'
)
```

Would you consider the addition of such an option? I am happy to work on it. Not sure what it should be called though…

**Comment by Shinigami92** [comment]
I would also want this to be kept to a minimum  
So if there are only `2` attributes => don't break even if they are 240 columns long

But if they are `5?` or more always break, even if they are below my configured `120` printWitdh

**Comment by lehni** [comment]
Great to hear, and good points! I'll play around with this a bit and see where I end up. So happy to hear about your opinion regarding the core philosophy. I do share that view ;)

**Comment by lehni** [comment]
Perhaps as simple as this: `maxAttributesOnSingleLine: 1`

**Comment by Shinigami92** [comment]
I more and more thing about that it was a bad idea to introduce options like `attributeSeparator`, `closingBracketPosition` and `commentPreserveSpaces` (I think I will deprecate these 3 and instead use their `pug*` equivalents)

So we directly should use `pugMaxAttributesOnSingleLine`

**Comment by lehni** [comment]
Agreed! I only use those anyway. BTW, I noticed there is no mention of `pugAttributeSeparator`, `pugClosingBracketPosition`,  `pugCommentPreserveSpaces` in the README. It only states:

> All these six Prettier options have an alias e.g.

But those _six_ aren't actually any of the three I mentioned above.

**Comment by Shinigami92** [comment]
Yeah I know, I meant the alias equivalents and not the own options
But now you have also introduced `pugArrowParens` etc
So yes if you like you can update the `README.md` in a dedicated PR and check it entirely of out of date things :slightly_smiling_face:
