### ISSUE TITLE
Bug: Formatter not working in conjunction with Vetur

### ISSUE THREAD

**Issue by aaronguernsey** [prettier/plugin-pug#124]
## Input

```
<template lang="pug">
button.hello( class="world" disabled @click="handleClick"  )
</template>
```
## Expected Output

```
<template lang="pug">
button.hello.world( 
  disabled
  @click="handleClick"  
)
</template>
```

## Actual Output

```
<template lang="pug">
button.hello.world( disabled, @click="handleClick"  )
</template>
```

## Additional Context
I'm using VS Code with the Vetur extension. My project has a `.prettierrc` file with the options

```
{
  "semi": false,
  "arrowParens": "always",
  "printWidth": 600,
  "pugAttributeSeparator": "none",
  "pugWrapAttributesThreshold": 0
}
```

If I remove any `plugin-pug` config settings, prettier works, but then it collapses all pug attributes to a single line. Am I doing something wrong when setting this up?

There are no additional VS Code settings aside from setting Vetur's default pug formatter to prettier.

Thanks in advance! All I'm looking for is forcing attributes on the next line and not adding commas between attributes 😄

**Comment by Shinigami92** [comment]
🤣 You are toooo fast ^^ 1.8.0 isn't even released yet 😄 

`pugWrapAttributesThreshold` will be in the next release 1.8.0

**Comment by aaronguernsey** [comment]
Haha, that's my bad! And you're equally too fast with the quick response 😆 

What about the `pugAttributeSeparator`?

And until 1.8.0 is there a way to prevent collapsing to a single line?

**Comment by Shinigami92** [comment]
Yes, `pugAttributeSeparator` should work, if it's not just use `attributeSeparator` 🤔 and I need to look into it

No currently no other way for collapsing 

https://github.com/prettier/plugin-pug/compare/1.7.0...master

**Comment by aaronguernsey** [comment]
Okay, thanks for the help! It seems like adding any additional settings outside of the first three prevents formatting.

I suppose this may not be a plugin issue, so I'll just move on without formatting for now, and you can close this issue. 

```
{
  "semi": false,
  "arrowParens": "always",
  "printWidth": 600
  // Adding any settings below prevents formatting
  // "attributeSeparator": "none"
  // "pugAttributeSeparator": "none"
}
```

**Comment by Shinigami92** [comment]
The option "attributeSeparator": "none" is really new (1.7.0)
I think vetur needs to update: https://github.com/vuejs/vetur/blob/master/server/package.json#L24

**Comment by lehni** [comment]
I think if your project has a newer `@prettier/plugin-pug` in its dependency, then Vetur / Prettier will pick that one up instead?

**Comment by aaronguernsey** [comment]
@lehni That's what I thought, but once I added any additional settings to my `.prettierrc` it stopped formatting. 

This works:
```
{
  "semi": false,
  "arrowParens": "always",
  "printWidth": 600
}
```

This does not:
```
{
  "semi": false,
  "arrowParens": "always",
  "printWidth": 600,
  "pugAttributeSeparator": "none"
}
```

**Comment by Shinigami92** [comment]
You could try "resolution" https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by aaronguernsey** [comment]
Okay, I think I figured it out.
@Shinigami92 I think it is related to your comment:
> The option "attributeSeparator": "none" is really new (1.7.0)
> I think vetur needs to update: https://github.com/vuejs/vetur/blob/master/server/package.json#L24

I had to downgrade Vetur's version to `0.27.3`, and then any `@prettier/plugin-pug` settings work. I will open a request on the Vetur repo and see about getting them to update to the current version.
