### ISSUE TITLE
Boolean attributes quotes pattern

### ISSUE THREAD

**Issue by SkyaTura** [prettier/plugin-pug#128]
## Request / Idea
Give the possibility to choose between use empty quotes or remove them when working with boolean attributes.

## Input

```pug
input(readonly="" disabled)
```

### `'none'`
```pug
input(readonly disabled)
```

### `'all'`
```pug
input(readonly="" disabled="")
```

### `'as-is'` **default**
```pug
input(readonly="" disabled)
```

### `'all'` with _exceptions_:
```javascript
const pugEmptyAttributes = 'all'
const pugEmptyAttributesExceptions = ['^@']
```

```pug
input(readonly disabled @click="")
```

### ~_as-needed_ ? on Vue or Angular this also may be necessary~
([why not](https://github.com/prettier/plugin-pug/issues/128#issuecomment-704034813))

```pug
input(readonly disabled @click="")
```

**Comment by SkyaTura** [comment]
## Options proposition

```typescript
const pugEmptyAttributesPattern = 'as-is' | 'all' | 'none'
const pugEmptyAttributesExceptions = string[]
```

In order to maintain the "agnosticism" of the library, maybe it's better to provide a list of regex strings with exceptions to the rule instead of defining framework-specific settings, as previously discussed in #22

**Comment by SkyaTura** [comment]
@Shinigami92 do you think it's too much options to create specific rules?

### Example
```typescript
type pugEmptyAttributes = 'as-is' | 'all' | 'none'
type pugEmptyAttributesKeep = string[]
type pugEmptyAttributesRemove = string[]
```

### Input
```javascript
const pugEmptyAttributes = 'all'
const pugEmptyAttributesRemove = ['disabled']
const pugEmptyAttributesKeep = ['^@']
```

```pug
input(foo="" disabled="" @click)
```

### Output
```pug
input(foo="" disabled @click="")
```

**Comment by Shinigami92** [comment]
First of all, yes
However, I haven't considered this problem long enough

First off, I'd suggest aiming for consistency, not just style

Therefore, perhaps in the first iteration of this feature no special exceptions should be made, which are then not used either way

Or do you have a special case in a real project?

---

Also take into account that incorrect use can lead to problems with e.g. test tools: https://github.com/vuejs/vue-test-utils/issues/1210#issuecomment-484327439

**Comment by SkyaTura** [comment]
I've managed to achieve a stable implementation _(tested on my projects)_ with only two options.

However, if the input is `Foo(#boom)`, it won't do anything and this would lead to problems as you pointed, which could be prevented by using 2 options for exceptions
