### ISSUE TITLE
Bug: Does not work when source contains for...of statement (Vue)

### ISSUE THREAD

**Issue by dlindenkreuz** [prettier/plugin-pug#129]
When the pug source code contains a for...of statement, the formatter bails and doesn't do anything in the pug segment.

Replace `v-for="x of quux"` with `v-for="x in quux"` in the input and everything works as intended.

## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.7.0        |
| Prettier | v2.1.0        |
| Node     | v12.18.3        |
| OS       | mac |

## Input

```pug
<!-- Test.vue -->
<template lang="pug">
.test( foo  bar="123" v-for="x of quux")
  | baz {{ quux}}
</template>

<style scoped lang="scss">
.test {
  color:  red;
}
</style>

<script>


export default {
  name: 'Test',
  data: () => ({quux: 'tobi'}),
};
</script>
```

## Actual Output

```vue
<!-- Test.vue -->
<template lang="pug">
.test( foo  bar="123" v-for="x of quux")
  | baz {{ quux}}
</template>

<style scoped lang="scss">
.test {
  color: red;
}
</style>

<script>
export default {
  name: "Test",
  data: () => ({ quux: "tobi" }),
};
</script>
```

## Expected Output

```vue
<!-- Test.vue -->
<template lang="pug">
.test(foo, bar="123", v-for="x of quux")
  | baz {{ quux }}
</template>

<style scoped lang="scss">
.test {
  color: red;
}
</style>

<script>
export default {
  name: "Test",
  data: () => ({ quux: "tobi" }),
};
</script>
```

**Comment by Shinigami92** [comment]
I'm sorry that currently other features are in pipeline for 1.8 release, so this needs to wait a bit for 1.9 or so

Some things beside:

Did you mean `v-for="x in quux"` instead of `v-for="x of quux"` in `expected`-section?

Also I need to investigate if this is maybe a bug of prettier itself or maybe just a feature request and not a bug ^^

**Comment by dlindenkreuz** [comment]
No worries, take your time.

The expected output contains `v-for="x in quux"` just like the input. Prettier should not change that.

When the input contains for...in instead of for...of, the output should contain the for...in statement as well.

**Comment by Shinigami92** [comment]
@dlindenkreuz Ok thanks for reporting
It's a bug, and it's on plugin's side

**Comment by Shinigami92** [comment]
Uff..nevermind, confused me by my own written try-catch :thinking: 
Maybe it is a prettier bug...
Need to dig into it
