### ISSUE TITLE
Bug: conversion of literals can replace the wrong content

### ISSUE THREAD

**Issue by lehni** [prettier/plugin-pug#133]
After having worked a bit with this part of the code, it just occurred to me that there could be this theoretical scenario where the use of `replace()` will replace the wrong part of the content, because it's run on the full result, not just the current element:

## Input

```pug
p
  | Just some text mentioning
  code div#id
  | or perhaps it talks about
  code div.class
div(id="id")
div(class="class")
```

## Expected Output

```pug
p
  | Just some text mentioning
  code div#id
  | or perhaps it talks about
  code div.class
#id
.class
```

## Actual Output

```pug
p
  | Just some text mentioning
  code #id
  | or perhaps it talks about
  code .class
div#id
div.class
```

I have ideas for how to fix this, will work on that next.

**Comment by Shinigami92** [comment]
Just in case, if you create a new PR, could you now use directly the repo instead of the fork? Then I can also help work and it's easier for me to checkout and review and also resolve merge conflicts :smile:

**Comment by lehni** [comment]
Yes I was thinking already that I should have done that yesterday. Will do so with this one!

**Comment by Shinigami92** [comment]
Are these two things?

`code div#id` instead of `code #id`
and
`div#id` instead of `#id` <-- This one was known to me since initial project setup XD but I was too lazy cause a second format resolved it :D

**Comment by lehni** [comment]
The point is that when you have `div#id` anywhere in your content, it'll get replaced as well. Maybe this makes it clearer:

```pug
p
  | Just some text mentioning "div#id"
  | or perhaps it talks about "div.class"
div(id="id")
div(class="class")
```

The use of `code` tags doesn't have anything to do with the problem
