### ISSUE TITLE
Bug: Plain Text is not always handled correctly

### ISSUE THREAD

**Issue by lehni** [prettier/plugin-pug#135]
## Input

In the following example, after formatting the plain-text on the last line is no longer correctly nested and does not appear with the `|` sign in front of it.

```pug
span
  | Click here:
  a(href="mailto:hi@gmail.com")
    | hi@gmail.com
  | to get in touch with us
```

## Expected Output

```pug
span
  | Click here:
  a(href="mailto:hi@gmail.com")
    | hi@gmail.com
  | to get in touch with us
```

## Actual Output

```pug
span
  | Click here:
  a(href="mailto:hi@gmail.com")
    | hi@gmail.com
to get in touch with us
```

**Comment by lehni** [comment]
Interestingly enough, when I write it like this, it works correctly:

```pug
span
  | Click here:
  a(href="mailto:hi@gmail.com") hi@gmail.com
  | to get in touch with us
```

**Comment by Shinigami92** [comment]
Can you assign your self and label these issues and PRs? Or should I manage this? :slightly_smiling_face:
