### ISSUE TITLE
Bug: Wrong parentheses placement in Vue v-for directive 

### ISSUE THREAD

**Issue by lehni** [prettier/plugin-pug#137]
When using v-for, the plugin adds parentheses around the full expression instead of just the loop variables, breaking the loop:

## Input

```pug
template(v-for="entry, index in list")
```

## Expected Output

```pug
template(v-for="(entry, index) in list")
```

## Actual Output

The plugin adds parentheses around the full expression, breaking the loop: 

```pug
template(v-for="(entry, index in list)")
```

## Error

```
Errors compiling template:
invalid expression: Unexpected token ) in list)
Raw expression: v-for="(entry, index in list)"
```

**Comment by Shinigami92** [comment]
Is this related with #129?

**Comment by lehni** [comment]
I don't know enough about Vue handling in the plugin to be able to tell right now…

**Comment by Shinigami92** [comment]
https://github.com/prettier/plugin-pug/blob/a220e916f79f067cf3cba605f237906e18ae9182/src/printer.ts#L289

https://github.com/prettier/plugin-pug/blob/a220e916f79f067cf3cba605f237906e18ae9182/src/printer.ts#L384-L397

https://github.com/prettier/plugin-pug/blob/a220e916f79f067cf3cba605f237906e18ae9182/src/printer.ts#L653-L656

**Comment by lehni** [comment]
Hmmm I need to look into this more. But `v-for` expressions aren't actually JS, so I don't think prettier should just handle them.

**Comment by Shinigami92** [comment]
You should read my discussion with Fisker: https://github.com/prettier/plugin-pug/pull/132#issuecomment-703273340
Prettier actually already format `v-for` in html
I'm calling these internal parsers

**Comment by lehni** [comment]
Ah ok!

**Comment by lehni** [comment]
Maybe we need to wait for this to land: https://github.com/prettier/prettier/pull/9225

**Comment by Shinigami92** [comment]
Oh didn't noticed that this isn't released yet :+1:

**Comment by Shinigami92** [comment]
@lehni Oh re-reading your initial issue description... and seeing that something like `entry, index in list` isn't valid syntax for the parser
So the parser cannot handle it correctly
I don't think I can solve this in a somewhat correct way and it would be better to just let handle such a syntax by a user
So the user needs to correctly write the syntax like `(entry, index) in list` and then the format can be applied correctly

I will label this issue with `wontfix` for now
If you know a better way of handling this, please explain and/or feel free to create a PR

**Comment by lehni** [comment]
Yes I agree, let's close this!
