### ISSUE TITLE
Bug: More issues with plain-text and nesting

### ISSUE THREAD

**Issue by lehni** [prettier/plugin-pug#138]
I thought I tackled this in #135, but there is more to it. When there is more nesting, then things end up on the wrong level:

## Input

```pug
div
  div
    | Click here:
    a(href="mailto:hi@gmail.com")
      | hi@gmail.com
    | to get in touch with us
```

## Expected Output

```pug
div
  div
    | Click here:
    a(href="mailto:hi@gmail.com")
      | hi@gmail.com
    | to get in touch with us
```

## Actual Output

```pug
div
  div
    | Click here:
    a(href="mailto:hi@gmail.com")
      | hi@gmail.com
  | to get in touch with us
```

The last line is on the wrong level, it should be indented one level further

**Comment by Shinigami92** [comment]
Looks like a need of `computedIndent` in line https://github.com/prettier/plugin-pug/blob/a220e916f79f067cf3cba605f237906e18ae9182/src/printer.ts#L899 to me

Hopefully this can guide you

**Comment by lehni** [comment]
Yes I just found that out also! :D

**Comment by Shinigami92** [comment]
@lehni Are you directly affected by this bug?
Or can we wait on some other PRs before releasing the next version?

**Comment by lehni** [comment]
@Shinigami92 I am, but it's easy enough to work around. I can wait for more PRs!

```pug
div
  div
    | Click here:
    a(href="mailto:hi@gmail.com")
      | hi@gmail.com
    // TODO: Remove once this is released: https://github.com/prettier/plugin-pug/issues/138
    | to get in touch with us
```
