### ISSUE TITLE
Start with tab in vue component

### ISSUE THREAD

**Issue by jessielaf** [prettier/plugin-pug#140]
## Request / Idea
First of all thanks for this library!

I usually start my pug with two spaces or 1 tab in my Vue template. I have recently installed prettier 2 and prettier pug and I have not found this option yet. I searched through the options but I could not find one to satisfy this need. Maybe I looked over it.

## Input

```pug
<template lang="pug">
div
  h1 Hellp
</template>
```

## Expected Output

```pug
<template lang="pug">
  div
    h1 Hellp
</template>

```

**Comment by Shinigami92** [comment]
So you requesting something like [vue-files-script-and-style-tags-indentation](https://prettier.io/docs/en/options.html#vue-files-script-and-style-tags-indentation), but `vue-files-template-tag-indentation`?

I'm thinking about if we should ask prettier itself to do this instead of my plugin :thinking: 
@fisker Any objection?

**Comment by fisker** [comment]
I don't think Prettier going to accept it, especially the `template` in html is already indented.

**Comment by Shinigami92** [comment]
Ok, then we need to implement this option into the plugin

**Comment by Shinigami92** [comment]
I don't think it's good idea to name it `vue-files-template-tag-indentation` when it's provided from our plugin
So maybe we should name it `pug-vue-files-template-tag-indentation`
But are there any other frameworks that behave the same as vue?

E.g. embedded in markdown, I do **not** think it's a useful option, cause there is no use case where it's useful

**Comment by jessielaf** [comment]
From my understanding Vue is the only js framework that has single-file components and uses HTML or pug in this way. The other SFC frameworks I know of are react and svelte. Both have different syntaxes.

**Comment by lehni** [comment]
Svelte has single-file components, and from my understanding you can use pug for templates there too:

**Comment by Shinigami92** [comment]
https://github.com/sveltejs/svelte-preprocess#built-in-support-for-commonly-used-languages

**Comment by Shinigami92** [comment]
Ok so `pug-vue-files-template-tag-indentation` is not a good name!

Maybe `pug-template-file-tag-indentation`?

**Comment by lehni** [comment]
`pugEmbededTemplateIndentation`

**Comment by Shinigami92** [comment]
I don't like it, cause markdown is also embedded and will not be indented

**Comment by Shinigami92** [comment]
I think we should go with `pugTemplateTagIndentation`, so without related to `file` cause that's just confusing in this context

... but ... now I see that could colide with e.g. vue's `template` tag synatx :thinking:  damn it

Maybe `pugSfcIndentation`?

**Comment by Shinigami92** [comment]
I started (quite finished ^^) this feature request
But we need to find a stable name for this options, so it doesn't collide with other feature request in the future

---

Also I think the current tests are not well enough to handle some special cases

---

@fisker Is there a way I can find out that the code is currently embedded in a `vue` or `svelte` file or if it is just e.g. markdown?
So can I find out the **_outer_** parser?

Cause someone wants to provide examples in a `README.md` and also use it in `.vue` files and just want to format everything `prettier --write .`
And this should only indent the SFC files

**Comment by fisker** [comment]
[`options.parentParser`](https://github.com/prettier/prettier/blob/86ad2997685a9ac86617502531e9d203976d23ea/src/main/multiparser.js#L39)

**Comment by Shinigami92** [comment]
Wow thank you @fisker 
Apparently I found out that there is a _mystery_ `embeddedInHtml`
I think that is even better, cause it may cover also `svelte` instead of only `vue`

I also need to add these both to DefinitelyTyped
I will add it into my https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47626 so I don't need to add a second PR

**Comment by Shinigami92** [comment]
Ok last step is missing: give it a stable name

1. `pugSfcIndentation`?
2. `pugSingleFileComponentIndentation`?
3. `pugTemplateTagIndentation`?
4. `pugTemplateTagFileIndentation`?
5. _something different_?

**Comment by lehni** [comment]
> > `pugEmbededTemplateIndentation`?
> 
> I don't like it, cause markdown is also embedded and will not be indented

But markdown does not have anything to do with `<template>`?

**Comment by lehni** [comment]
> 1. `pugSfcIndentation`?

This sounds quite obscure I think.

> 2. `pugSingleFileComponentIndentation`?

This is better, but it's not really the indentation of the component, it's the indentation of the pug template inside the component…

> 3. `pugTemplateTagIndentation`?

Probably the best one of the options!

> 4. `pugTemplateTagFileIndentation`?

I don't think `File` needs to be mentioned? They're all in files, after all :)

> 5. _something different_?

**Comment by Shinigami92** [comment]
@lehni Thanks, that was helpful

For `pugTemplateTagIndentation`

```vue
<template lang="pug">
  v-tooltip(bottom)
    //- vvv Below is a "template"-tag
    template(v-slot:activator="{ on, attrs }")
      v-btn(v-on="on", v-bind="attrs", color="primary", dark) Button
    span Tooltip
</template>
```

That is what I meant with a template tag

**Comment by fisker** [comment]
How about  `pugIndentationInVueSFCRootTemplate` or `pugIndentationForVueSFCRootTemplate`

**Comment by Shinigami92** [comment]
It's not `vue` related, it should also work for `svelte`

**Comment by lehni** [comment]
`eslint-plugin-vue` has a rule for this. It's simply called `html-indent`: https://eslint.vuejs.org/rules/html-indent.html#rule-details

**Comment by Shinigami92** [comment]
Finally some new types from DefinitelyTyped arrived

I made my decision to `pugSingleFileComponentIndentation`, because I think it is the best fit and doesn't conflict with to many other things like `template`, `vue`-related or `embedded-markdown`

@lehni Could you have a last review over my PR, then I will merge it and provide a new release

**Comment by lehni** [comment]
@Shinigami92 very swamped with work these days, I don't think I'll find the time for another 10 days or so :/

Regarding naming: I would `pugSingleFileComponentIndentation` not to be a boolean value, but to describe the amount of indentation?

**Comment by Shinigami92** [comment]
I think it's ok, I will merge it now

**Comment by lehni** [comment]
Probably too late now, but I just found out that Vetur has this setting here:

`vetur.format.styleInitialIndent`. It used to also have `vetur.format.templateInitialIndent`, but that got removed again, not sure why…

**Comment by Shinigami92** [comment]
Yeah, I already created a release
I prefer incremental releases with a minimum of breaking changes
