### ISSUE TITLE
Bug: [coc.nvim] pug not supported by prettier

### ISSUE THREAD

**Issue by ryeballar** [prettier/plugin-pug#150]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.10.0        |
| Prettier | v2.1.2        |
| Node     | v12.19.0        |
| OS       | linux |

## The Issue

[coc-prettier](https://github.com/neoclide/coc-prettier) is a fork of [prettier-vscode](https://github.com/prettier/prettier-vscode) where its implementation heavily relies on the the file type defined in **vim** and the **vscodeLanguageIds** defined in the plugin being supported. 

I'm currently using [vim-pug](https://github.com/junegunn/vim-plug) for syntax highlighting which maps any file or buffer with the extension **.pug** or **.jade**  to the **pug** editor file type. **coc-prettier** will compare that **pug** file type against all **vscodeLanguageIds** gathered across different prettier plugins which will unfortunately fail since **plugin-prettier** defines **vscodeLanguageIds** with `[ "jade" ]`.

### Resolution:
Add **pug** in the **vscodeLanguageIds** array.

**Comment by Shinigami92** [comment]
This has now been released `1.10.1`
Thank you for using my plugin and for being part of the pug community 🤗
