### ISSUE TITLE
Bug: Invalid pugWrapAttributesPattern value

### ISSUE THREAD

**Issue by basaran** [prettier/plugin-pug#160]
## Info

```
"@prettier/plugin-pug": "^1.10.1",
"prettier": "^2.2.0",
"framework, vue"
"node, Welcome to Node.js v14.6.0."
"os, WSL"
```

## Prettier config

```js
module.exports = {
    trailingComma: "es5",
    tabWidth: 4,
    semi: true,
    printWidth: 120,
    singleQuote: false,
    // htmlWhitespaceSensitivity: "ignore",
    overrides: [
        {
            files: "*.vue",
            options: {
                tabWidth: 4,
                pugTabWidth: 4,
                pugPrintWidth: 120,
                pugSingleFileComponentIndentation: false,
                // pugWrapAttributesThreshold: 1,
                pugWrapAttributesPattern: 1,
                pugSortAttributes: "asc",
                // pugClosingBracketPosition: "last-line",
            },
        },
    ],
};
```
## Additional Context
While running prettier through the CLI, it returns

`[error] Invalid pugWrapAttributesPattern value. Expected a string, but received 1.`

Setting to `pugWrapAttributesPattern: "1",` removes the error, but it appears the output is not being processed as defined in `pugWrapAttributesPattern` documentation. It seems to be ignored.

**Comment by Shinigami92** [comment]
Oh I found a problem in `README.md` related to this, so maybe sorry for the confusion and I will fix that.  (https://github.com/prettier/plugin-pug/commit/c79a993ed451983523b743931ebeb1f6585a464b)

`pugWrapAttributesThreshold` takes a number,
but `pugWrapAttributesPattern` takes indeed a string or more a 'pattern'.
So yes: `1` is not an acceptable input.
A pattern could be e.g. `"pugWrapAttributesPattern": "^v-(if|else|for)"`

**Comment by basaran** [comment]
Thank you very much, it is as expected now.
