### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by prphntm63** [prettier/plugin-pug#164]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.10.1                  |
| Prettier  | v2.1.2                  |
| Framework | none |
| Node      | v12.14.0                  |
| OS        | win,mac           |

## Prettier config

```json
{}
```

## Input

```pug
              .form-group
								h4 User Information
```
-->

## Output or Error

```bash
[error] views\scoresheet.pug: Error: Pug:180:1
[error]     178|
[error]     179|               .form-group
[error]   > 180|                                                                h4 User Information
[error] ---------^
[error]     181|                                                                .form-row.py-1
[error]     182|                                                                        .form-group.col-sm-2.col-form-label
[error]     183|                                                                                label(for="entry_number") Entry Number
[error]
[error] Invalid indentation, you can use tabs or spaces but not both
[error]     at makeError (C:\projects\BJCP-Scoresheet\node_modules\pug-error\index.js:34:13)
[error]     at Lexer.error (C:\projects\BJCP-Scoresheet\node_modules\pug-lexer\index.js:62:15)
[error]     at Lexer.indent (C:\projects\BJCP-Scoresheet\node_modules\pug-lexer\index.js:1493:14)
[error]     at Lexer.callLexerFunction (C:\projects\BJCP-Scoresheet\node_modules\pug-lexer\index.js:1642:23)
[error]     at Lexer.advance (C:\projects\BJCP-Scoresheet\node_modules\pug-lexer\index.js:1683:12)
[error]     at Lexer.callLexerFunction (C:\projects\BJCP-Scoresheet\node_modules\pug-lexer\index.js:1642:23)
[error]     at Lexer.getTokens (C:\projects\BJCP-Scoresheet\node_modules\pug-lexer\index.js:1701:12)
[error]     at lex (C:\projects\BJCP-Scoresheet\node_modules\pug-lexer\index.js:12:42)
[error]     at Object.parse (C:\projects\BJCP-Scoresheet\node_modules\@prettier\plugin-pug\dist\index.js:38:32)
[error]     at Object.parse (C:\projects\BJCP-Scoresheet\node_modules\prettier\index.js:13575:19)
```

## Expected Output

```pug
              .form-group
                h4 User Information
```

## Additional Context
One of our contributors accidentally committed with tabs instead of spaces. We are using husky pre commit hook to trigger lint. I think it would be a good feature (or option) to be able to rewrite tabs as spaces (or enforce space-only) in template files instead of crashing.

**Comment by Shinigami92** [comment]
I cannot do this due to limitations of the pug parser :slightly_frowning_face:  
I'm very sorry but I need to forward you to https://github.com/pugjs/pug

As you can see in the stacktrace, the error was thrown by pug's `Lexer`, it's not an error of my formatter itself. Indeed this error is thrown before this plugin even starts with the formatting process.

You can also paste your example into https://pughtml.com and see the error.

**Comment by prphntm63** [comment]
Ah I see. Thanks!
