### ISSUE TITLE
Bug: Plugin removes all content of the Pug files!

### ISSUE THREAD

**Issue by aero31aero** [prettier/plugin-pug#168]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.13.0                 |
| Prettier  | v2.0.5                  |
| Framework | none                    |
| Node      | v14.9.0                 |
| OS        | linux                   |

## Prettier config

```js
module.exports = {
    trailingComma: 'es5',
    tabWidth: 4,
    semi: true,
    singleQuote: true,
};

```

## Input

```pug
html
	head
		title Rohitt - Fun Stuff
	body
		h1 Fun Stuff
		ul
			li
				strong
					a(href="/fun/neon-dystopia") Neon Dystopia
				br
				span Atmos 2017 Homepage, Three JS.
			li
				strong
					a(href="/fun/rabbit") Frightened Rabbit [WIP]
				br
				span Visuals for a song I love, Three JS.
```

## Output or Error

The diff is:

```diff
diff --git src/fun/index.pug src/fun/index.pug
index a27d450..e69de29 100644
--- src/fun/index.pug
+++ src/fun/index.pug
@@ -1,16 +0,0 @@
-html
-	head
-		title Rohitt - Fun Stuff
-	body
-		h1 Fun Stuff
-		ul
-			li
-				strong
-					a(href="/fun/neon-dystopia") Neon Dystopia
-				br
-				span Atmos 2017 Homepage, Three JS.
-			li
-				strong
-					a(href="/fun/rabbit") Frightened Rabbit [WIP]
-				br
-				span Visuals for a song I love, Three JS.

```

## Expected Output

Anything else at all.

## Additional Context

Just running `prettier src/fun/index.pug --write` removes all content from the pug file. Reproducible across the project (running on all files with a glob clears all pug files).

## Severity

I think this is a very severe bug. I was running this on a git repo and all my files I'd edited this session were open in my editor but its quite likely someone might accidentally run this before their first commit or after significant work but before committing. Bailing out would be better than blanking the files.

**Comment by Shinigami92** [comment]
Could you retry with prettier >= 2.1? If this is the problem I need to clarify this in peer dependencies.

**Comment by Shinigami92** [comment]
Yes, that is it! Will bump peerDependencies to >= 2.1
