### ISSUE TITLE
Bug: Plugin removes unescaped interpolations

### ISSUE THREAD

**Issue by andreubotella** [prettier/plugin-pug#169]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.13.0                  |
| Prettier  | v2.2.1                  |
| Framework | none |
| Node      | v14.14.0                  |
| OS        | linux           |

## Prettier config

```json
{}
```

## Input

```pug
script.
    doSomething(!{JSON.stringify(pugLocalVariable)});
```

## Output or Error

```
Unhandled token for pipeless script tag: {"type":"interpolated-code","loc":{"start":{"line":2,"column":17},"end":{"line":2,"column":52}},"mustEscape":false,"buffer":true,"val":"JSON.stringify(pugLocalVariable)"}
```

```pug
script.
  doSomething();
```

## Expected Output

`prettier` should not raise an error or remove the interpolation.

## Additional Context

This bug is a regression; version 1.10.1 of `@prettier/plugin-pug` doesn't have it.

**Comment by Shinigami92** [comment]
Thanks for the report 👍
And yes, the pipeless script tag progression is a new feature 
I will add a test for your case and investigative what's wrong with it

**Comment by Shinigami92** [comment]
I identified the problem and working on a warning handling system for that
So in the future you will get notified that you are using invalid JS, but it may be ok cause of interpolated code and then you can ignore the warning
