### ISSUE TITLE
Use with eslint configuration

### ISSUE THREAD

**Issue by nnfans** [prettier/plugin-pug#17]
Can I use this with eslint configuration?

**Comment by Shinigami92** [comment]
Can you provide more information about your problem?
I mainly use TSLint myself and therefore do not know what is not working with eslint.

**Comment by nnfans** [comment]
Where can I put the plugin pug inside the .eslintrc.json ?
`// .eslintrc.json`
`{
  "extends": ["airbnb", "plugin:prettier/recommended"]
}`

**Comment by Shinigami92** [comment]
I think you misunderstood something.
This plugin is for Prettier and not for eslint.
The only place where you can address it is the prettier config file.

**Comment by nnfans** [comment]
oh, I see. Thanks
