### ISSUE TITLE
Bug: Blank lines contain spaces in inline syntax

### ISSUE THREAD

**Issue by yuheiy** [prettier/plugin-pug#171]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.13.1                  |
| Prettier  | v2.2.1                  |
| Framework | none |
| Node      | v12.20.0                  |
| OS        | mac           |

## Prettier config

I’m using the default config.

## Input

```pug
style.
  .a {
  }

  .b {
  }
```

The 4th line contains no spaces.

## Output or Error

```pug
style.
  .a {
  }
  
  .b {
  }
```

The 4th line contains spaces.

## Expected Output

```pug
style.
  .a {
  }

  .b {
  }
```

**Comment by Shinigami92** [comment]
Hi @yuheiy 
Sorry for that bug 😅

So I think I know were this is coming from

The red part is the whole indentation of the code from pug and the green part is the indented-managed part from js  
<img src="https://user-images.githubusercontent.com/7195563/101889788-19e24f00-3ba0-11eb-9ed1-f30c8b3cfa40.png" width="60px"/>

So we have to iterate over the formatted lines and check where blank lines occur and the remove the indentation in the red part :thinking:  
Could be harder than it reads

---

Are you willing to create a PR for that?
Should be something around here: https://github.com/prettier/plugin-pug/blob/1c7af90eb2d63ac6df216907f4afcbfd3f3445f9/src/printer.ts#L1080-L1186
You can extend this test https://github.com/prettier/plugin-pug/tree/main/tests/issues/issue-158 or create a new one

I'm currently into Cyberpunk 2077 😛 so if I should work on this, it could take some days
But I'm happy to review and merge PRs

**Comment by Shinigami92** [comment]
@yuheiy I'm so sorry for you that I currently also taking holiday from GitHub :sweat_smile:  
I have around 60h playtime in CP2077 and still not finished with it 🥰
Also I have some private meetings here and there as christmas events

So tldr: I think I will come back to GitHub in January

Have a greate time and stay safe :smiley:

**Comment by Shinigami92** [comment]
Oh my god, I'm so sorry for you @yuheiy that I let you wait so long
I started working on this and thought "OK that may be hard to find and fix, but let's do it"
... and then ... it was a one-liner :facepalm: 

https://github.com/prettier/plugin-pug/pull/175/files#diff-35264771cf86f41ef7b7d56b764142b299a8bd2a972b2316e4e3e92e13056500R1171

:rofl:  

But I will let make a co-worker a review on this so I don't miss anything, but you can expect a release of `1.13.2` or similar in the next few hours/days

**Comment by yuheiy** [comment]
Great! Thank you so much!

**Comment by Shinigami92** [comment]
There it is :heart: https://www.npmjs.com/package/@prettier/plugin-pug/v/1.13.2
