### ISSUE TITLE
Bug: Error: Invalid --pug-bracket-spacing value. Expected null, false, "" or "true", but received true.

### ISSUE THREAD

**Issue by jinrongni** [prettier/plugin-pug#174]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.13.1                 |
| Prettier  | v2.2.1                  |
| Framework | vue |
| Node      | v12.20.0                  |
| OS        | win           |

## Prettier config

```json
{
	"semi": true,
	"singleQuote": true,
	"bracketSpacing": true,
	"printWidth": 80,
	"tabWidth": 4,
	"useTabs": true,
	"quoteProps": "as-needed",
	"jsxSingleQuote": false,
	"trailingComma": "all",
	"jsxBracketSameLine": true,
	"arrowParens": "always",
	"endOfLine": "crlf",
	"embeddedLanguageFormatting": "auto",
	"pugBracketSpacing": true,
	"pugSingleQuote": false
}

```

## Input

```pug

```

## Output or Error

```bash
npx prettier --write .
```

## Expected Output

```pug

```

## Additional Context
when i am running the command `npx prettier --write .`   
I got an Error : [error] Error: Invalid --pug-bracket-spacing value. Expected null, false, "" or "true", but received true.

so,  i changed  `"pugBracketSpacing": true` to `"pugBracketSpacing": "true"` , this time, i got [PugPrinter:formatText]:  Error: Invalid bracketSpacing value. Expected true or false, but received "true".

**Comment by Shinigami92** [comment]
https://github.com/prettier/prettier/issues/9204
