### ISSUE TITLE
pugWrapAttributesThreshold: wrap according to line length (printWidth)

### ISSUE THREAD

**Issue by Heziode** [prettier/plugin-pug#178]
## Request / Idea

Add a way to wrap tags that have a length greater than the line length.

## Input

```pug
div.inline-flex.w-full.t-input(:class=`{
  "ring border-blue-300 rounded": inputFocused,
  // Animation
  "duration-100 ease-in-out transition": true,
}`)
  slot(name="before" v-bind:isInvalid="isInvalid" v-bind:isDisabled="isDisabled" v-bind:inputFocused="inputFocused")
  LegacyTNumberInput(v-model="newValue" :as="as" :name="inputId" :value="value" :isReadOnly="isReadOnly" :isInvalid="isInvalid" :isDisabled="isDisabled" :isFullWidth="isFullWidth" :isRequired="isRequired", :inputId="inputId" :placeholder="placeholder" :type="type" :autoComplete="autoComplete" :maxlength="maxlength" :rows="rows" @focus="focused" @blur="onBlur")
  slot(name="after" v-bind:isInvalid="isInvalid" v-bind:isDisabled="isDisabled" v-bind:inputFocused="inputFocused")
```

## Expected Output

With `printWidth: 120`, we should have something like that:

```pug
div.inline-flex.w-full.t-input(:class=`{
  "ring border-blue-300 rounded": inputFocused,
  // Animation
  "duration-100 ease-in-out transition": true,
}`)
  slot(name="before" v-bind:isInvalid="isInvalid" v-bind:isDisabled="isDisabled" v-bind:inputFocused="inputFocused")
  LegacyTNumberInput(v-model="newValue"
    :as="as"
    :name="inputId"
    :value="value"
    :isReadOnly="isReadOnly"
    :isInvalid="isInvalid"
    :isDisabled="isDisabled"
    :isFullWidth="isFullWidth"
    :isRequired="isRequired",
    :inputId="inputId"
    :placeholder="placeholder"
    :type="type"
    :autoComplete="autoComplete"
    :maxlength="maxlength"
    :rows="rows"
    @focus="focused"
    @blur="onBlur")
  slot(name="after" v-bind:isInvalid="isInvalid" v-bind:isDisabled="isDisabled" v-bind:inputFocused="inputFocused")
```

**Comment by Shinigami92** [comment]
Could you be more specific and also add a `Actual Output` + your prettier config?

Also we have `pugWrapAttributesThreshold`.
- What did you tried with that?
- What can it not solve for you?

_sorry if I misunderstood some parts, I'm german native_

---

<img src="https://user-images.githubusercontent.com/7195563/107875539-e930d580-6ec0-11eb-8a11-4ba1d0684bba.png" width="300px" />

Also I saw this in your expected output :eyes: 
I don't think I will support this kind of _"don't wrap first attribute, but all others"_

**Comment by Heziode** [comment]
I do not use the pug plugin for prettier currently, because it does not provide what I needs.

> I don't think I will support this kind of "don't wrap first attribute, but all others"

Indeed, this should be wrapped too.

---

The behaviour of the wrap attribute treshold I needs is: if attributs in tags exceeds the `printWidth` setting, so the tag will be wrapped, one attriubte per line.

**Comment by Shinigami92** [comment]
I'm confused and hope that I don't misunderstood anything
But isn't this the default behavior of our plugin? You only need to set `printWidth` to 120 and that's it :thinking:

**Comment by Heziode** [comment]
Indeed, you are right.

I didn't understand this example in documentation:

> -1 -> Only wrap attributes as needed.
> Example:
> input(type="text")
> input(type="text", value="my_value", name="my_name")
