### ISSUE TITLE
Handle v-slot formatting

### ISSUE THREAD

**Issue by Shinigami92** [prettier/plugin-pug#180]
## Input

```pug
v-slide-group(v-model="model")
  v-slide-item(v-slot="{  active , toggle  }")
    v-card
      //- ...
  v-slide-item(v-slot="{  active,  toggle  }")
    v-card
      //- ...
```

## Expected Output

```pug
v-slide-group(v-model="model")
  v-slide-item(v-slot="{ active, toggle }")
    v-card
      //- ...
  v-slide-item(v-slot="{ active, toggle }")
    v-card
      //- ...
```

**Comment by kaangokdemir** [comment]
Even it works well with default and named slots, unfortunately it still not works well with [named slot shorthand](https://vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand)

## Input

```pug
template(#header='{    alpha,beta }')
template(v-slot:footer='{    alpha,beta }')
```

## Expected Output

```pug
template(#header='{ alpha, beta }') // ❌ Not formats
template(v-slot:footer='{ alpha, beta }') ✅ Formats
```

**Comment by Shinigami92** [comment]
@kaangokdemir Could you open a new issue? That will create a new issue number and I need that cause my test directories (and changelog entries) are referencing these issue numbers.
