### ISSUE TITLE
Bug: svelte pug formatting

### ISSUE THREAD

**Issue by basaran** [prettier/plugin-pug#201]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.13.5                  |
| Prettier  | v2.2.1                  |
| Framework | svelte |
| Node      | v15.4                  |
| OS        | wsl           |

## Additional Context

In reference to [https://github.com/sveltejs/language-tools/issues/951](https://github.com/sveltejs/language-tools/issues/951) please find the basic repository below.

[https://github.com/basaran/svelte-pug](https://github.com/basaran/svelte-pug)

Additional information has been provided in the readme.md for setting up the environment.

**Comment by dummdidumm** [comment]
This reproduction will not work for Svelte files because right now `prettier-plugin-svelte` which formats Svelte files completely skips formatting the pug template part. I will play around with removing that limitation in the next few days. Until then, for reproduction, it is best to focus on the parts inside `<template lang="pug">`. You might copy the stuff inside out of there and see how it is formatted with prettier-pug.

**Comment by Shinigami92** [comment]
Thanks, I already saw that it seems that svelte uses single braces, e.g. `{name}`

This may currently not work in my plugin and I will need to fix that

**Comment by basaran** [comment]
It seems the language functions are prefixed with `+` when inside the pug template.  You can replace the `App.svelte` with this.

Things appear to formatting just fine.

```
<script>
export let name;
export let cats = [
    {id: 'J---aiyznGQ', name: 'Keyboard Cat'},
    {id: 'z_AbfPXTKms', name: 'Maru'},
    {id: 'OUtn3pvWmpg', name: 'Henri The Existential Cat'},
];
</script>

<template lang="pug">
main
    h1 Hello {name}!
    p
        | Visit the
        a(href='https://svelte.dev/tutorial')
            | Svelte tutorial
            | to learn how to build Svelte
            | apps.
    p
        +each('cats as cat')
            a(href='{cat.id}') {cat.name}
            | !{' '}
</template>
```

**Comment by Shinigami92** [comment]
The `+` prefixed tags will be just recognized as pug-mixins https://pugjs.org/language/mixins.html

I don't know if I will have time today, tomorrow or at very least over weekend

**Comment by basaran** [comment]
Sure thing. Meanwhile, I will keep reading the docs :)
