### ISSUE TITLE
bug: Can not handle `<!DOCTYPE html>` correctly

### ISSUE THREAD

**Issue by JounQin** [prettier/plugin-pug#24]
```pug
<!DOCTYPE html>
html(lang="zh-Hans-CN")
  head
    meta(charset="UTF-8")
    meta(name="viewport", content="width=device-width, initial-scale=1.0")
    meta(http-equiv="X-UA-Compatible", content="ie=edge")
    link(rel="manifest", href="/manifest.json")
    title #{ htmlWebpackPlugin.options.title }
  body
    #root
```

```sh
Error: Unhandled token: {"type":"text-html","loc":{"start":{"line":1,"column":1},"end":{"line":1,"column":16}},"val":"<!DOCTYPE html>"}
```

**Comment by Shinigami92** [comment]
I will fix this soon (maybe next 24h hours)

In the meanwhile try [pug doctype](https://pugjs.org/language/doctype.html)

**Comment by JounQin** [comment]
Yep, I've migrated to built-in doctype.

The original content is generated by VSCode emmet.

**Comment by Shinigami92** [comment]
Ok, I will also deal with VSCode. Maybe we can also change the emmet generated output.
But now I will start to smash this bug 😀

**Comment by Shinigami92** [comment]
I need your opinion.
Would you like it if this plugin can turn that into `pug-code` or should the `text-html` remain untouched?

So this
```pug
<!DOCTYPE html>
```
could become this
```pug
doctype html
```

**Comment by JounQin** [comment]
I'd love to use `doctype html` which seems more consistent.

**Comment by Shinigami92** [comment]
Ok, then I will rebuild it so that it will be transformed to pug

**Comment by Shinigami92** [comment]
Ok, in this first iteration, I'm just going to transform singleline `text-html`,
because I have to track wrapping tags and really need to do a lot more things ^^'

**Comment by JounQin** [comment]
@Shinigami92 Thx for fixing this. I think we could use [angular-html-parser](http://github.com/ikatyang/angular-html-parser) which should be available in `prettier` `parsers` in this case rather than trying to implement parse again which could be buggy and inconsistent with `prettier`'s built-in html behavior.

**Comment by Shinigami92** [comment]
Released as [1.0.4](https://www.npmjs.com/package/@prettier/plugin-pug/v/1.0.4)
Thanks for using my Plugin 😃

Ok, thanks for mentioning, I will open a new issue and then I will enjoy my weekend 😋

**Comment by JounQin** [comment]
Happy weekend.

**Comment by Shinigami92** [comment]
Created an Issue to find the right place of the emmet abbrevation `html:5`
https://github.com/microsoft/vscode/issues/81993
