### ISSUE TITLE
Bug: pugAttributeSeparator='as-needed' breaks quotes of the preceding attribute value

### ISSUE THREAD

**Issue by lukaromih** [prettier/plugin-pug#255]
### Plugin Version

v1.16.0

### Prettier Version

v2.3.2

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

v10.19.0

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Prettier config

```json
overrides:
  - files: "*.pug"
    options:
      semi: false
      singleQuote: true
      trailingComma: none
      arrowParens: avoid
      pugAttributeSeparator: as-needed
```

### Input

```pug
doctype html
html
  head
    title= title
    link(rel='stylesheet' , href='/stylesheets/style.css')
  body
    block content
```

### Output or Error

```bash
doctype html
html
  head
    title= title
    link(rel="stylesheet" href='/stylesheets/style.css')
  body
    block content
```

### Expected Output

```pug
doctype html
html
  head
    title= title
    link(rel='stylesheet' href='/stylesheets/style.css')
  body
    block content
```

### Additional Context

When using the option _pugAttributeSeparator: as-needed_, the pugin breaks quotes around attribute values, which are followed by atleast one space before comma and the following attribute key/value pair.
This can seen in the 5th line of my example:

> link(rel='stylesheet' , href='/stylesheets/style.css')

will get rewritten by the plugin as:

> link(rel="stylesheet" href='/stylesheets/style.css')

When I rerun it the 2nd time, it ends up correctly, as:

> link(rel='stylesheet' href='/stylesheets/style.css')

With more than 2 attributes, it only breaks the ones which have atleast one space before the comma and the following attributes, but correctly sets up the attribues, which are immediately followed by a comma.

Without the _singleQuote: true_ option, it will break the quotes to the single quotes. Put simply, it always breaks the quotes since it applies exactly the opposite of what you have set.

**Comment by Shinigami92** [comment]
I think I know this issue, but was too lazy to fix it, cause nobody reported it... Until now... Now I think I have to finally fix it :sweat_smile: 
_How dare you_ :rofl:  
I will work tomorrow on this :+1:

**Comment by Shinigami92** [comment]
@lukaromih Please test out [v1.16.1-0](https://www.npmjs.com/package/@prettier/plugin-pug/v/1.16.1-0).

**Comment by lukaromih** [comment]
Well, that was fast and the fix definitely works. Thanks!

Would you recommend that I update the dependent projects with version v1.16.1-0 (how stable is it?) or wait for the next patch/minor version?

As far as I'm concerned, this issue has been resolved 👍👏

**Comment by Shinigami92** [comment]
`v1.16.1-0` could potentially be exactly what `v1.16.1` will be :slightly_smiling_face:  
I just wanted to be safe and I will try it on next working-day on my companies project
