### ISSUE TITLE
Bug: Can't preserve backticks

### ISSUE THREAD

**Issue by jd-0001** [prettier/plugin-pug#261]
## Info

| Tool      | Version  |
| --------- | -------- |
| Plugin    | v1.16.0  |
| Prettier  | v2.3.2   |
| Framework | none     |
| Node      | v14.16.1 |
| OS        | linux    |

## Prettier config

```json
{
    "arrowParens": "avoid",
    "bracketSpacing": true,
    "htmlWhitespaceSensitivity": "css",
    "insertPragma": false,
    "jsxBracketSameLine": false,
    "jsxSingleQuote": true,
    "printWidth": 120,
    "proseWrap": "preserve",
    "quoteProps": "as-needed",
    "requirePragma": false,
    "semi": true,
    "singleQuote": true,
    "tabWidth": 2,
    "trailingComma": "all",
    "useTabs": false,
    "vueIndentScriptAndStyle": false,
    "endOfLine": "lf",
    "pugSingleQuote": false,
    "pugTabWidth": 4,
    "pugEmptyAttributes": "none"
}

```

## Input

> Below backtick usage is converted to double quotes

```pug
img(src=post.img, class=`${roundness}`)
```

## Output or Error

> backtick converted to double quotes so generated HTML have below incorrect class

```html
<img class="${roundness}" src="https://picsum.photos/400/225">
```

## Expected Output

```html
<img class="rounded-lg" src="https://picsum.photos/400/225">
```

## Additional Context

`roundness` is a global variable:

```bash
pug -O "{roundness: 'rounded-lg'}" -w ./index.pug -o . -P
```

So, How can I make this plugin preserve backtick when I save in vs code?

**Comment by Shinigami92** [comment]
Will check if this is a bug

Could you check that your input is really valid?

![image](https://user-images.githubusercontent.com/7195563/127375689-0615ce38-b0f3-4bff-92cd-74aeb1f975a5.png)

Seems there is a missing backtick?

Could you check if it's a regression of https://github.com/prettier/plugin-pug/commit/ff0715c83f7e9c69d354978aa4be33ee9e626931#diff-4ade25325a6cd7d1cca619364c84d19bfa47e6939a2c1b38d065767255b8f86eR168

So could you try roll back a version (to 1.15.x) and see if it's "fixed" then?

If so, I think I will have time next weekend to fix that

**Comment by jd-0001** [comment]
Sorry, I had full code and removed the unwanted class so I missed the ending backtick but my input is correct.

Will try your suggestion of rolling back and will let you know.

**Comment by Shinigami92** [comment]
I found out that it is a specific bug for `class` attribute (maybe also for `id`)
So other attributes will work fine

And yes, it was introduced by the mentioned change

**Comment by Yann-prak** [comment]
> Will check if this is a bug
> 
> Could you check that your input is really valid?
> 
> ![image](https://user-images.githubusercontent.com/7195563/127375689-0615ce38-b0f3-4bff-92cd-74aeb1f975a5.png)
> 
> Seems there is a missing backtick?
> 
> Could you check if it's a regression of [ff0715c#diff-4ade25325a6cd7d1cca619364c84d19bfa47e6939a2c1b38d065767255b8f86eR168](https://github.com/prettier/plugin-pug/commit/ff0715c83f7e9c69d354978aa4be33ee9e626931#diff-4ade25325a6cd7d1cca619364c84d19bfa47e6939a2c1b38d065767255b8f86eR168)
> 
> So could you try roll back a version (to 1.15.x) and see if it's "fixed" then?
> 
> If so, I think I will have time next weekend to fix that

Hi,

I've roll back to 1.15.x and the bug doesn't exist anymore. Maybe your changes affected the way prettier interpret backticks.

**Comment by Yann-prak** [comment]
> I found out that it is a specific bug for `class` attribute (maybe also for `id`)
> So other attributes will work fine
> 
> And yes, it was introduced by the mentioned change

Yes ! The only way I can reproduce the bug is on the id attr.

**Comment by Shinigami92** [comment]
The fix need to be applied here

https://github.com/prettier/plugin-pug/blob/39c50cebddb3058d908a3d62dfc24eaae92c5907/src/printer.ts#L790-L848
