### ISSUE TITLE
Bug: Can not handle Vue slot shortcut syntax

### ISSUE THREAD

**Issue by backbone87** [prettier/plugin-pug#289]
### Plugin Version

master

### Prettier Version

^2.3

### Which frameworks are affected?

- [ ] none
- [X] vue
- [ ] angular
- [ ] svelte

### Node Version

14

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Prettier config

```json
{
  printWidth: 120,
  singleQuote: true,
  trailingComma: 'all',
  pugAttributeSeparator: 'none',
  pugFramework: 'vue',
  pugSingleFileComponentIndentation: true,
  pugSingleQuote: false,
}
```

### Input

```pug
my-component(foo="bar", #default="{ baz }")
```

### Output or Error

```bash
my-component(foo="bar", #default="{ baz }")
```

### Expected Output

```pug
my-component(foo="bar" #default="{ baz }")
```

### Additional Context

it just does not format the content at all (via VS code). removing the destructuring will make it work

**Comment by Shinigami92** [comment]
Please use `v-slot:...` until I can fix this.
It's a know bug

**Comment by Shinigami92** [comment]
I had a home PC crash yesterday 😢 
So sorry that I may not response in next few days, I will try to recover my system and set this as my prio...
