### ISSUE TITLE
Bug: Inline js has indentation issues

### ISSUE THREAD

**Issue by Dradows** [prettier/plugin-pug#307]
### Plugin Version

1.17.1

### Prettier Version

2.4.1

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

14.17.1

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Prettier config

```json
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "*.pug",
  "parser": "pug"
}
```

### Input

```pug
script(src='javascripts/echarts.js')
script(src='javascripts/jquery-3.6.0.js')
link(href='stylesheets/bootstrap.css', rel='stylesheet')
script(src='javascripts/bootstrap.bundle.js')

#main(style='width: 100%; height: 1000px')
script.
    var chartDom = document.getElementById("main");
    var myChart = echarts.init(chartDom, null, { renderer: "canvas" });
    let option;
    fetch("data/chResults.json")
        .then(data => data.json())
        .then(json => {
            console.log(json);
        });
```

### Output or Error

```bash
script(src='javascripts/echarts.js')
script(src='javascripts/jquery-3.6.0.js')
link(href='stylesheets/bootstrap.css', rel='stylesheet')
script(src='javascripts/bootstrap.bundle.js')

#main(style='width: 100%; height: 1000px')
script.
    var chartDom = document.getElementById("main");
    var myChart = echarts.init(chartDom, null, { renderer: "canvas" });
    let option;
    fetch("data/chResults.json")
      .then(data => data.json())
      .then(json => {
        console.log(json);
      });
```

### Expected Output

```pug
script(src='javascripts/echarts.js')
script(src='javascripts/jquery-3.6.0.js')
link(href='stylesheets/bootstrap.css', rel='stylesheet')
script(src='javascripts/bootstrap.bundle.js')

#main(style='width: 100%; height: 1000px')
script.
    var chartDom = document.getElementById("main");
    var myChart = echarts.init(chartDom, null, { renderer: "canvas" });
    let option;
    fetch("data/chResults.json")
        .then(data => data.json())
        .then(json => {
            console.log(json);
        });
```

### Additional Context

The difference between quotation is acceptable, but the difference between indentation seriously affects programming

**Comment by Dradows** [comment]
A temporary solution is to change "useTabs": false

**Comment by Shinigami92** [comment]
I think we miss to add `tabWidth` here:

https://github.com/prettier/plugin-pug/blob/6657b733ca11ad4faeab5db454f7d7298b80e00f/src/printer.ts#L241-L249

If you are faster than me AND want to take credits for the fix, feel free to create a PR 🙂 
Also pls add a test like a copy of one of https://github.com/prettier/plugin-pug/tree/main/tests/issues

**Comment by Dradows** [comment]
> I think we miss to add `tabWidth` here:
> 
> https://github.com/prettier/plugin-pug/blob/6657b733ca11ad4faeab5db454f7d7298b80e00f/src/printer.ts#L241-L249
> 
> If you are faster than me AND want to take credits for the fix, feel free to create a PR 🙂 Also pls add a test like a copy of one of https://github.com/prettier/plugin-pug/tree/main/tests/issues

Problem solved and PR submitted😉

**Comment by Shinigami92** [comment]
I may release it tomorrow as a 1.17.2
