### ISSUE TITLE
Configurable class literal location

### ISSUE THREAD

**Issue by shadowgate15** [prettier/plugin-pug#313]
## Request / Idea
Have an option to set where class literals will be placed.

## Input

```pug
#class-after-attributes.class.class-2(type='text')

#class-before-attributes(type='text').class.class-2
```

## Expected Output

```pug
#class-after-attributes(type='text').class.class-2

#class-before-attributes.class.class-2(type='text')
```

**Comment by Shinigami92** [comment]
Should the same be applied to `id` literals?
Could you describe >**why**< do you want this feature?

**Comment by shadowgate15** [comment]
It is just strictly an opinion of formatting. same as wanting to have attributes sorted.

**Comment by Shinigami92** [comment]
Are you interested in creating a PR for that? 🙂
If you need any help, feel free to ask. You can look how other options are implemented and orient on that.

**Comment by shadowgate15** [comment]
yep will do! just going to work on the quotes PR first then I can work on this one.
