### ISSUE TITLE
Refer to pug documentation for prettier formatting

### ISSUE THREAD

**Issue by Applelo** [prettier/plugin-pug#32]
It would be nice if you refer more to pug formatting like they do in there documentation.
For example use space instead of comma to separate attributes.

If it's possible, add an parameter to make Class and ID Literal optional.

**Comment by Shinigami92** [comment]
That was a design decision

https://github.com/prettier/plugin-pug/issues/13

You can use prettiers override to set the option

**Comment by Shinigami92** [comment]
I updated the README.md

https://github.com/prettier/plugin-pug/blob/master/README.md#prettier-pug-specific-options

If you miss anything, please let me know
Otherwise feel free to close this issue

**Comment by Applelo** [comment]
Like I said, is it possible to make optional the formatting of Class / ID to literal ?

**Comment by Shinigami92** [comment]
> Like I said, is it possible to make optional the formatting of Class / ID to literal ?

Have to think about it
I think I wont do it in the next few day, because I target bugs first and have prio to other projects

**Comment by Shinigami92** [comment]
I extracted the feature request into it's own issue so it is more clean and better managable for me
