### ISSUE TITLE
Documentation: installing Prettier without --save-exact

### ISSUE THREAD

**Issue by PavelS-BM** [prettier/plugin-pug#323]
Mayby it would be better to install prettier with --save-exact flag. In Prettier docs, they are stating that you should use:

> npm install --save-dev --save-exact prettier

because:

> Install an exact version of Prettier locally in your project. This makes sure that everyone in the project gets the exact same version of Prettier. Even a patch release of Prettier can result in slightly different formatting, so you wouldn’t want different team members using different versions and formatting each other’s changes back and forth.

And when you do 

> npm add --save-dev prettier @prettier/plugin-pug

If you install prettier from their docs, and then install pug plugin from this docs, you will rewrite "--save-exact" flag in package.json. So it can produce unwanted changes in your package.json.

**Comment by Shinigami92** [comment]
Would you like to change this in the docs?

**Comment by PavelS-BM** [comment]
I will kindly leave it to you.

**Comment by Shinigami92** [comment]
closed via https://github.com/prettier/plugin-pug/commit/2643f4703b062e631f874e6f5f1040e0b98a273f
