### ISSUE TITLE
Bug: Prettier is consolidating mixin objects to single-line

### ISSUE THREAD

**Issue by ekfuhrmann** [prettier/plugin-pug#324]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.19.0                  |
| Prettier  | v2.2.1                  |
| Framework | none |
| Node      | 14.17.5                  |
| OS        | win           |

## Prettier config

```json
{
  "semi": true,
  "trailingComma": "es5",
  "singleQuote": true,
  "printWidth": 80,
  "tabWidth": 2,
  "endOfLine": "auto"
}
```

## Input

```pug
mixin section-intro(content)
  section.section.section--intro(data-chameleon='black')
    .wrapper
      .section__header
        if content.subhead
          p.section__subhead.enter.enter--bottom!= content.subhead
        p.section__heading.enter.enter--bottom.enter--delay-1!= content.heading

      .section__row
        each column in content.content
          .section__column
            .section__content.enter.enter--bottom.enter--delay-2
              p.section__content-subhead!= column.subhead
              each paragraph in column.text
                p.section__content-text!= paragraph

        if content.image
          img.section__image.enter.enter--bottom.enter--delay-3(src=`/${relativeRoot}assets/images/work/${content.image}`, alt='')

      if block
        block

+section-intro({
  subhead: 'Introduction',
  heading: 'Helping candidates and employers connect through a streamlined platform, all while ensuring no one is left out. ',
  content: [
    {
      subhead: 'The Problem',
      text: ['Employers are eager to higher a diverse workforce, but struggle to manage the daunting process to access talent that meets their needs. Underrepresented job seekers often go unnoticed or worse, get passed up based on existing market biases. ']
    },
    {
      subhead: 'The Solution',
      text: ['Create a network that prioritizes inclusivity and transparency by uniting job seekers with employers based on their common strengths.  For employers and admins, use thoughtful automation to encourage autonomy.']
    }
  ]
})


```

## Output or Error
```pug
+section-intro({ subhead: 'Introduction', heading: 'Helping candidates and employers connect through a streamlined platform, all while ensuring no one is left out. ', content: [ { subhead: 'The Problem', text: ['Employers are eager to higher a diverse workforce, but struggle to manage the daunting process to access talent that meets their needs. Underrepresented job seekers often go unnoticed or worse, get passed up based on existing market biases. '] }, { subhead: 'The Solution', text: ['Create a network that prioritizes inclusivity and transparency by uniting job seekers with employers based on their common strengths. For employers and admins, use thoughtful automation to encourage autonomy.'] } ] })
```

## Expected Output

```pug
+section-intro({
  subhead: 'Introduction',
  heading: 'Helping candidates and employers connect through a streamlined platform, all while ensuring no one is left out. ',
  content: [
    {
      subhead: 'The Problem',
      text: ['Employers are eager to higher a diverse workforce, but struggle to manage the daunting process to access talent that meets their needs. Underrepresented job seekers often go unnoticed or worse, get passed up based on existing market biases. ']
    },
    {
      subhead: 'The Solution',
      text: ['Create a network that prioritizes inclusivity and transparency by uniting job seekers with employers based on their common strengths.  For employers and admins, use thoughtful automation to encourage autonomy.']
    }
  ]
})
```

**Comment by Shinigami92** [comment]
I already tried to format this, but it's very hard and error-prone :confused: 
Theoretically `args` can be anything, it could be json, or a comma separated list of args that contains e.g. also json as one arg, and I cannot find out where a comma of param args is or a json comma is.
So to totally fix this, we would need to have this feature: https://github.com/pugjs/pug/issues/3214

I will also close this issue due to duplicate to https://github.com/prettier/plugin-pug/issues/66

**Comment by Shinigami92** [comment]
I added your example to https://github.com/prettier/plugin-pug/pull/288/files#diff-1e245999f5f4f9addd82061304d8883000cec3136adf05176737f29ecdb667d8R26

**Comment by ekfuhrmann** [comment]
Oh gosh, I forgot I created that issue... 🤦. I did a search ahead of time and just didn't do a good enough job, sorry about the duplicate, though I am happy that this example may be more useful.

Thanks again for everything.

**Comment by Shinigami92** [comment]
Sadly pug is kinda really dead in maintenance :sob: 
They didn't even response in anyway to my request
Beside that, I think this is VERY hard to implement and maybe it's easier for now to find a workaround like to extract the json content to a `var`/`let`/`const` and pass it as arg
That way it gets formatted, I think

**Comment by ekfuhrmann** [comment]
yeah, that's fair. I have a rather large legacy project that just was not formatted that way and I dread the thought of going back through and reconfiguring it. I'll most likely just avoid using puglint for that older project so as to not have to deal with it, but on other projects I'll use the `var` pattern to work around it.

Here's to hoping Pug begins to get maintained again one day, in the meantime I really do appreciate all that you do for the community.
