### ISSUE TITLE
Bug: JSON-serialized data inside an element attribute (used by cloudflare analytics) produce parsing error

### ISSUE THREAD

**Issue by tkafka** [prettier/plugin-pug#335]
### Plugin Version

1.19.2

### Prettier Version

2.5.1

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

17.2.0

### Which operating systems have you used?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Prettier config

```json
{
	singleQuote: true,
	useTabs: true,
	tabWidth: 1,
	arrowParens: 'always',
	semi: false,
	printWidth: 200,
}
```

### Input

```pug
mixin cloudflareTracking
	script(defer, type='text/javascript', src='https://static.cloudflareinsights.com/beacon.min.js', data-cf-beacon='{ "token": "7db89a9eb26e4af9b566c980e43a3a22" }')
```

### Output or Error

```bash
The following expression could not be formatted correctly. Please try to fix it yourself and if there is a problem, please open a bug issue: "token": "7db89a9eb26e4af9b566c980e43a3a22"
```

### Expected Output

```pug
Parsed successfuly
```

### Additional Context

It seems that JSON-serialized data inside an attribute (as cloudflare analytics uses) cannot be parsed.

**Comment by Shinigami92** [comment]
I assume it is coming from here:

https://github.com/prettier/plugin-pug/blob/c9596d257cbc63fc3782dda01bf059fd4e6a16b7/src/printer.ts#L697-L714

I'm happy to review a pull request if you open one.
Until then, consider it as a logged warning.
Maybe you have e.g. the possibility to workaround it with extracting it into a variable or so.

**Comment by tkafka** [comment]
@Shinigami92 Thank you, yes, this seems to be the cause. It didn't occur to me to extract the string to a variable, and it helped - thank you!
