### ISSUE TITLE
Bug: inconsistencies when using `pugSingleQuote: false` with `singleQuote: true` in vue SFCs templates

### ISSUE THREAD

**Issue by qnp** [prettier/plugin-pug#339]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.19.2                  |
| Prettier  | v2.5.1                  |
| Framework | vue           |
| Node      | v16.13.2                  |
| OS        | mac           |

## Prettier config

```json
{
  "singleQuote": true,
  "pugSingleQuote": false
}
```

```vue
<template lang="pug">
  my-component(:my-prop="someJavascript('here')")
  div {{ someJavascript('here') }}
</template>
```

## Output

After formatting, we obtain:
```pug
my-component(:my-prop="someJavascript('here')")
div {{ someJavascript("here") }}
```
Code between "mustaches" `{{ ... }}` is *not* pug markup but Javascript code, however it does not respect the `singleQuote: true` prettier option.

## Expected Output

Everything between "mustaches" `{{ ... }}` must be treated as Javascript code, so that the `singleQuote: true` prettier option is respected, as follows:
```diff
- div {{ someJavascript("here") }}
+ div {{ someJavascript('here') }}
```

## Additional Context

May be related to https://github.com/prettier/plugin-pug/issues/66 ?

## Minimal repro playground
[issue-prettier-plugin-pug-quotes.zip](https://github.com/prettier/plugin-pug/files/8132294/issue-prettier-plugin-pug-quotes.zip)

**Comment by qnp** [comment]
To clarify : this is not a `vue` SFC related issue only, I mean, it also appears in plain pug using _mustache_ patterns – as you can see in my minimal repro example. The point is we encounter it while using `vue` SFC because we always need these _mustache_ patterns in vue templates.

**Comment by Shinigami92** [comment]
Have not touched the code base for a while, so I currently don't know the exact location where to start.
It would be very welcome if you jump into it and open a PR, I can then try to help you if you have some questions.

I have a https://github.com/prettier/plugin-pug/blob/main/CONTRIBUTING.md and it is very helpful to just copy one of the tests and create a `tests/issues/issue-339/issue-339.test.ts`

**Comment by qnp** [comment]
RIght, @Shinigami92 I'll try to dive in soon and make the fixes.

**Comment by Shinigami92** [comment]
> RIght, @Shinigami92 I'll try to dive in soon and make the fixes.

Any progress?

**Comment by qnp** [comment]
@Shinigami92, I have found the origin of the issue, but I need your insight.

The problem lies here : https://github.com/prettier/plugin-pug/blob/40bd2707cf65d937cfb24c3e2d925e25da79ab0c/src/printer.ts#L267-L277,
where `pug<X>` options have been introduced to override `<X>` prettier options, useful in the case of Vue SFCs.

`this.codeInterpolationOptions` are passed where the code between `{{` `}}` is formatted, hence this is the pug override which is taken, if provided, whereas the matched code should be considered as pure *javascript* and treated with non-prefixed `singleQuote` options.

I have perfomed other tests with all the possible `pug<X>` options different from the `<X>` ones. I could not see any problems with the other ones. Indeed, the problem with `singleQuote` & `pugSingleQuote` options **is very specific** of Vue usage (sorry about [this wrong comment](https://github.com/prettier/plugin-pug/issues/339#issuecomment-1049785560) where attributes in quotes wrap javascript code.

So in order to have consistency in template interpolation using javascript code, you should not be doing
```
singleQuote: options.pugSingleQuote ?? options.singleQuote
```

However, as expected, removing the override breaks others tests:
- tests/options/singleQuote/single-false-pug-true/single-false-pug-true.test.ts
- tests/options/singleQuote/single-true-pug-false/single-true-pug-false.test.ts

So the solution would be the use a vue-specific options object (without `pugSingleQuote` override) in `frameworkFormat` function ?

**Comment by Shinigami92** [comment]
@qnp I would assume that we can specifically can override the option if text token was called 🤔 

Could you try to add an over-override here?

https://github.com/prettier/plugin-pug/blob/40bd2707cf65d937cfb24c3e2d925e25da79ab0c/src/printer.ts#L453-L463

Maybe like `const options: Options = { ...this.codeInterpolationOptions, singleQuote: options.singleQuote };` or so?!

**Comment by qnp** [comment]
It's exactly what I thought doing, I think this is the best solution. Keep in touch

**Comment by qnp** [comment]
https://github.com/prettier/plugin-pug/pull/354
