### ISSUE TITLE
Bug: Using pugClassNotation: 'as-is' reports Duplicate Attribute error in Vue/TS

### ISSUE THREAD

**Issue by sfrendpax8** [prettier/plugin-pug#392]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v2.0.0                  |
| Prettier  | v2.6.2                  |
| Framework | vue |
| Node      | v16                 |
| OS        | mac           |

## Prettier config

```
{
  plugins: [require.resolve('@prettier/plugin-pug')],

  singleQuote: true,
  trailingComma: 'all',
  semi: true,
  printWidth: 120,
  // prettier-ignore
  importOrder: [
    '^.*service.*$',
    '([./]|@/(.*)$)',
  ],
  importOrderSeparation: true,

  pugClassNotation: 'as-is',
  pugIdNotation: 'as-is',
  pugFramework: 'vue',
  pugSingleQuote: false,
  pugAttributeSeparator: 'none',
  pugSortAttributes: 'asc',
  pugSortAttributesBeginning: [
    '^v-if$',
    '^v-else-if$',
    '^v-else$',
    '^v-for$',
    '^v-model',
    '^:is$',
    '^:key$',
    '^v-on$',
    '^v-bind$',
    '^ref$',
    '^name$',
    '^:?type$',
    '^:value$',
    '^:?label$',
    '^:?src$',
  ],
  pugSortAttributesEnd: ['^:id', '^id', '^@click', '^@'],
}
```

## Input
```vue
<template lang="pug">
.sidebar(class="flex flex-col relative pb-28")
</template>
```

## Output or Error

```
Duplicate Attribute. vue(2)

```

## Additional Context
`pugClassNotation: 'as-is'`

Using Vue 3 with TypeScript and Tailwind.
The `class` attribute gets red underline and output in Problems console. The problem goes away if I remove the `.sidebar` class and put it inside of the class attribute instead, but we like to use class wrapper names for components. Code still compiles, just makes it look like we have lint issues.

The expected behavior would be that when setting is set to `as-is`, I can have classes in both places.

**Comment by Shinigami92** [comment]
No further response for one week
Feel free to reopen if needed
