### ISSUE TITLE
Add support for interpolation

### ISSUE THREAD

**Issue by Applelo** [prettier/plugin-pug#40]
Can you add the support for interpolation ?
See https://pugjs.org/language/interpolation.html

**Comment by Shinigami92** [comment]
Please provide me some code, so I can create a test for that

I heavily using TDD -> https://github.com/prettier/plugin-pug/tree/master/test/issues

**Comment by Applelo** [comment]
Ok so I try some test, the interpolation work but not with his case:

```
 - const el = 'div';
 - const test = 'hello';
 #{el}.test
   | !{text}
```
