### ISSUE TITLE
Bug: prettier-ignore removes script tag in PUG

### ISSUE THREAD

**Issue by kumardeepakxyz** [prettier/plugin-pug#402]
## Script tag is removed when ignoring

`prettier-ignore` removes script tag when ignored by `//- prettier-ignore` in PUG template.

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v2.1.1                  |
| Prettier  | v2.7.1                 |
| Framework | none |
| Node      | v16.16.0                  |
| OS        | mac           |

## Prettier config

```json
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "quoteProps": "as-needed",
  "jsxSingleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "bracketSameLine": true,
  "arrowParens": "avoid",
  "endOfLine": "lf",
  "embeddedLanguageFormatting": "off",

  "pugAttributeSeparator": "none",
  "pugClosingBracketPosition": "last-line",
  "pugWrapAttributesPattern": "-1"
}
```

## Input

```pug
//- SCRIPTS
script(async src='https://www.googletagmanager.com/gtag/js?id=AW-XXXXXXXXX')
//- prettier-ignore
script.
  window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'AW-XXXXXXXXX');
```

## Expected Output
It should ignore formatting of script tag and its code, **But it completely removes the script tag with the code inside.**

## OnSave - script tag gets deleted
![ezgif com-gif-maker](https://user-images.githubusercontent.com/36254505/178140469-0b24ad5b-9c59-43d6-8e4e-dfbb4aa56f64.gif)

**Comment by Shinigami92** [comment]
Please search for a workaround for the next two weeks
I will be in Singapore for the next two weeks
