### ISSUE TITLE
Allow empty curly brackets as attributes

### ISSUE THREAD

**Issue by joselcvarela** [prettier/plugin-pug#404]
## Request / Idea
Allow empty curly brackets as attributes, instead of removing them.

## Input

```pug
.text-red-400()&attributes(attributes)
```

## Expected Output

```pug
.text-red-400()&attributes(attributes)
```

## Additional Context
I just faced an issue using `.text-red-400&attributes(attributes)` because Tailwind thinks this whole thing is a class `text-red-400&attributes` as it does not generate the class `.text-red-400`.
If we allow empty curly brackets, then this example would be fixed by `.text-red-400()&attributes(attributes)`.
My current workaround is `.text-red-400(class="")&attributes(attributes)` but does not make much sense

**Comment by Shinigami92** [comment]
You should create a PR or wait for around 2 weeks 
I'm in Singapore making vacation
