### ISSUE TITLE
Common Pug format module not dependent on Prettier

### ISSUE THREAD

**Issue by johnsoncodehk** [prettier/plugin-pug#416]
## Request / Idea

Extract the core Pug format logic to single module that do not dependent on Prettier and embedded language context, so that we can use it for more environment.

**Comment by Shinigami92** [comment]
@johnsoncodehk Please watch https://github.com/Shinigami92/pug-fmt for updates

**Comment by Shinigami92** [comment]
This takes to much effort, sorry 🤷
