### ISSUE TITLE
Bug: Upon running prettier on PUG files space before and after 'a' tag disappear 

### ISSUE THREAD

**Issue by serferdinand2** [prettier/plugin-pug#417]
## Exapmple 
Code below:
```
p Please click 
        a(example.com) here
        |  to go to our link.
```              
changes upon running prettier to :

```
p Please click
      a(example.com) here
       | to go to our link.
```
The extra space just after the 'click' and after the pipe symbol is removed and the result is:

Please click[here](example.com)to go to our link.

And it should be: 

Please click [here](example.com) to go to our link.

**Comment by Shinigami92** [comment]
I think you are running into this: https://pugjs.org/language/plain-text.html#not-recommended
I suggest to rewrite your pug code to what is recommended: https://pugjs.org/language/plain-text.html#recommended-solutions

Please close this issue if that solved your problem, otherwise let me know why this couldn't help.

**Comment by jwerre** [comment]
Isn't the the point of Prettier? Feels like this is something that should be fixed with this extension.

**Comment by Shinigami92** [comment]
I agree to some point, but it could be that the `lexer` behind could return totally different result of tokens 🤔 
Would someone of you want to try that out with writing a test in the `tests/issues` folder and open a PR for it?

**Comment by jwerre** [comment]
Ya, I can do that

**Comment by jwerre** [comment]
Ok.. I made the test. I'll let you all figure out how to pass them. Good luck :)

**Comment by Shinigami92** [comment]
Thank you, might not have the time today, but hopefully over weekend :+1:
