### ISSUE TITLE
Bug: Space at the end of an element causes | and newlines to be inserted

### ISSUE THREAD

**Issue by richardsimko** [prettier/plugin-pug#439]
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v2.4.2                  |
| Prettier  | v2..8.8                  |
| Framework | vue |
| Node      | v19.0.0                  |
| OS        | mac           |

## Prettier config

```json
{

}
```

## Input

```vue
<template lang="pug">
.root //<----- extra space here
  .second
</template>
```

## Output or Error

```bash
Insert `|⏎··`
```

Output after formatting:
```vue
<template lang="pug">
.root 
  |
  |
  |
  |
  |
  |
  |
  |
  |
  |
  |
  |
  |
  .second
</template>
```

## Expected Output

```pug
.root
  .second
```

## Additional Context
Notice there is a space after `.root`. If I run the formatter on the code it won't be removed leading to it creating more newlines with `|` every time it's run.

**Comment by Shinigami92** [comment]
Related to https://github.com/prettier/plugin-pug/issues/425

**Comment by richardsimko** [comment]
This also seems to be a bug with plain templates:

```pug
.test 
  .inner
```

```pug
.test 
  |
  .inner
```

Each time the formatter is run an additional `|` is added.

**Comment by Shinigami92** [comment]
@richardsimko took me a while and potentially caused some headaches :laughing: 
but finally I fixed it :tada: 

Please checkout [v2.5.0](https://www.npmjs.com/package/@prettier/plugin-pug/v/2.5.0)
_Also note that NodeJS v14 is now not supported anymore_ :wink:

**Comment by richardsimko** [comment]
Thanks for the fix! It does indeed seem to have fixed standalone pug files, however `.vue` files still suffer from the same issue.

**Comment by Shinigami92** [comment]
uhm what?
the change I did was not releated to vue at all :thinking: 

Can you please open a new issue with example so I can track it?

**Comment by richardsimko** [comment]
Thanks for the fix! Works great :)
