### ISSUE TITLE
Bug: VSCode fails to format pug files with prettier@3.1.1 and higher

### ISSUE THREAD

**Issue by ladown** [prettier/plugin-pug#478]
### Plugin Version

v3.0.0

### Prettier Version

v3.1.1

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

v20.10.0

### Which operating systems have you used?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Prettier config

```json
{
  "plugins": ["@prettier/plugin-pug"],
  "tabWidth": 4,
  "singleQuote": true,
  "trailingComma": "all",
  "semi": true,
  "printWidth": 130,
  "useTabs": true,
  "jsxSingleQuote": true,
  "endOfLine": "auto",
  "bracketSameLine": false,
  "htmlWhitespaceSensitivity": "ignore",
  "pugAttributeSeparator": "none",
  "pugWrapAttributesThreshold": 1
}
```

### Input

```pug
script.
  const obj = { test: 1};
```

### Output or Error

```bash
There is no formatter for 'jade' files installed.
```

### Expected Output

```pug
script.
  const obj = { test: 1 };
```

### Additional Context

Hello!

I faced with the problem, that `prettier@3.1.1` and higher causes the problem, that `VSCode` doesn't format `Pug` files with `prettier`. If we install `prettier3.1.0` and lower it works fine. When we install `prettier@3.1.1` and higher, we see next indicator in footer panel of `VSCode`:

<img width="63" alt="image" src="https://github.com/prettier/plugin-pug/assets/68401113/83006f75-0b07-47f2-9765-70346c82988f">

When we try to format it with command `Format Document`, we will have the following notification:

<img width="340" alt="image" src="https://github.com/prettier/plugin-pug/assets/68401113/1eeba775-3893-4b6f-8604-9d1b50a1d3bc">

I also tried to set default formatter in `VSCode` settings and it didn't not help me. 

If we try to format `.pug` files from CLI, it works perfect

**Comment by Shinigami92** [comment]
Can you identify if this is an issue with the plugin, or maybe with the prettier version https://github.com/prettier/prettier/blob/main/CHANGELOG.md#311

**Comment by ladown** [comment]
I tested this issue with other plugins and figured out, that its connected with the `Prettier`

**Comment by ladown** [comment]
I found the solution. If we will override parser for `*.pug` files, it will work:
```json
{
  "plugins": ["@prettier/plugin-pug"],
  "overrides": [
    {
      "files": "*.pug",
      "options": {
        "parser": "pug"
      }
    }
  ]
}

```

**Comment by mhabsaoui** [comment]
Hi,
Same here, I have installed Prettier and the Pug plugin as DevDeps.
`"@prettier/plugin-pug": "^3.0.0"`
`"prettier": "^3.2.5"`

When trying to indent, I get same suggestion window from VSCode for Jade :-/ 
 
![Screenshot from 2024-02-16 20-01-14](https://github.com/prettier/plugin-pug/assets/18755135/b16051a5-356e-4f73-8c69-7133e12c5874)

**Comment by ladown** [comment]
Hello, @mhabsaoui !

Its a problem with prettier extension as i can see. Here you can learn more - https://github.com/prettier/prettier-vscode/issues/3253

As for me, i found a solution to add path to prettier config in VSCode JSON settings -- `"prettier.configPath": "./.prettierrc"`
