### ISSUE TITLE
An interpolation following an id collapses into it.

### ISSUE THREAD

**Issue by andreubotella** [prettier/plugin-pug#49]
The following valid pug code:
```pug
doctype html
html
  body
    h1#header #{title}
```
collapses into the following, which isn't valid pug:
```
doctype html
html
  body
    h1#header#{title}
```

This also happens with lone id's (`#header #{title}`) and unescaped interpolations (`!{title}`). It doesn't happen with classes (`h1.header #{title}`), though.

This seems to be a case of #27 that wasn't handled when the bug was closed.

**Comment by Shinigami92** [comment]
Should be fixed in [1.1.1](https://www.npmjs.com/package/@prettier/plugin-pug/v/1.1.1)
Somehow npm seems to need some time to realize that I have deployed a release
Hope a 20-minute fix was quick enough 😂

**Comment by andreubotella** [comment]
Wow, thanks so much!

It's not like I needed a fix immediately, but that was plenty fast. I'm fine with waiting for npm to catch up.

**Comment by Shinigami92** [comment]
You have given me a little sense in this lonely Sunday 🤷‍♂️
So thank you 😅

**Comment by andreubotella** [comment]
Any news from npm yet?

**Comment by Shinigami92** [comment]
> Any news from npm yet?

I have contacted the npm support 
Waiting on a reply

**Comment by Shinigami92** [comment]
@andreubotella There it is 🎉 

And look at the timestamp :D

![image](https://user-images.githubusercontent.com/7195563/70936061-e0850b00-2041-11ea-8242-c3448a1488c6.png)
