### ISSUE TITLE
ID Transformation breaks with special literals

### ISSUE THREAD

**Issue by leider** [prettier/plugin-pug#51]
`input("some[subkey]")` is converted to `input#some[subkey]`
This definitely does not compile

**Comment by Shinigami92** [comment]
Very interesting 🤔, I will examine it this evening

**Comment by leider** [comment]
it should say `input(id="some[subkey]")`

**Comment by Shinigami92** [comment]
> it should say `input(id="some[subkey]")`

you mean instead of `input("some[subkey]")`?

I think I have to parse the id's value and if there is something like `[` dont transform it
-> should be easy ^^

**Comment by leider** [comment]
new release will be appreciated!

**Comment by leider** [comment]
still broken in 1.1.2. Example:
```pug
.input-group
  select(id="kopf[kooperation]")
```

**Comment by leider** [comment]
myabe your test cases are slightly simplistic? ;)

**Comment by Shinigami92** [comment]
Have you cleaned your node_modules folder? Maybe there are conflicting files?!
Because when I add your new example to my test, it pass

**Comment by leider** [comment]
seems to have been a webstorm caching problem. restarting webstorm solved it
