### ISSUE TITLE
Wrongly formatted literal line

### ISSUE THREAD

**Issue by leider** [prettier/plugin-pug#52]
```pug
            | !{variableWithHtmlString}
```
is formatted to 
```pug
!{variableWithHtmlString}
```
Breaks rendering

**Comment by leider** [comment]
Two issues here:
1. indentation change
2. removal of "|"

**Comment by Shinigami92** [comment]
I couldn't reproduce the issue :(
Could you check my test files?

https://github.com/prettier/plugin-pug/pull/57/files

Maybe I need more content to test

**Comment by leider** [comment]
this is minimal example:
```pug
div
  a(href="")
    h6 A
  | !{veranstaltung.renderedPresseText()}
```

**Comment by Shinigami92** [comment]
> ```
> div
>   a(href="")
>     h6 A
>   | !{veranstaltung.renderedPresseText()}
> ```

Ja! Nun kann ich es reproduzieren 😉

**Comment by leider** [comment]
Das freut!

**Comment by leider** [comment]
That has been the show stopper for today's pleasure!

**Comment by Shinigami92** [comment]
Thats why I want to reflect the other things only as a workaround
- it's better code with the workaround
- it's not that urgent like this issue
- I can release the next version in the next few minutes :)

**Comment by leider** [comment]
Go for it

**Comment by Shinigami92** [comment]
Could you give me a GO for these "documentations"?
https://github.com/prettier/plugin-pug#some-workarounds

**Comment by leider** [comment]
For #53 only the workaround with template string works for me. Better remove the other proposal: input(onClick="methodname('" + variable + "', this)")

You can check it out, it will also transform to a non working variant.

**Comment by leider** [comment]
#54 is OK

**Comment by Shinigami92** [comment]
> For #53 only the workaround with template string works for me. Better remove the other proposal: input(onClick="methodname('" + variable + "', this)")
> 
> You can check it out, it will also transform to a non working variant.

Is it because you are forced to double quotes in this place?
Can you test if `input(onClick='methodname("' + variable + '", this)')` is working for you?

**Comment by Shinigami92** [comment]
Nevermind... I see 😒 OK this is a problem, but I would want to work on it later

**Comment by leider** [comment]
transforms to `input(onClick="methodname(\"' + variable + '\", this)")`
not ok

**Comment by Shinigami92** [comment]
https://www.npmjs.com/package/@prettier/plugin-pug/v/1.1.2 released 🎉
