### ISSUE TITLE
Wrong replacement of quotes

### ISSUE THREAD

**Issue by leider** [prettier/plugin-pug#53]
`input(onClick="methodname(\"" + variable + "\", this)")` is converted to `input(onClick="methodname(\"\" + variable + \"\", this)")`

this changes semantics massively

**Comment by Shinigami92** [comment]
Could this be the same as
`input(onClick="methodname('" + variable + "', this)")`
or
```input(onClick=`methodname("${variable}", this)`)```

you could also add the `"` inside the `methodname`-method

of course as a workaround at first

**Comment by leider** [comment]
yep. that should work as a workaround

**Comment by Shinigami92** [comment]
Is the workaround sufficient for you?
Should I add something to the readme?

**Comment by Shinigami92** [comment]
Closing as predecessor of #58
