### ISSUE TITLE
wrong replacement of class

### ISSUE THREAD

**Issue by leider** [prettier/plugin-pug#54]
`div(id = id, class = 'collapse' + (collapsed ? '' : ' show') + ' cardcontent')` is transformed to `.cardcontent(id=id, class="collapse' + (collapsed ? '' : ' show') + '")`

easy to see that that will break behaviour

**Comment by Shinigami92** [comment]
I have analyzed your example and I suggest you to rewrite your code
from
```pug
- const id = 42
- const collapsed = true
div(id=id, class='collapse' + (collapsed ? '' : ' show') + ' cardcontent')
```
to
```pug
- const id = 42
- const collapsed = true
.cardcontent.collapse(id=id, class=collapsed ? '' : 'show')
```

Example: https://pugjs.org/language/attributes.html

**Comment by leider** [comment]
I see. This way mixing .class notation with class= notation on one and the same node

**Comment by Shinigami92** [comment]
Is the workaround sufficient for you?
Should I add something to the readme?

**Comment by leider** [comment]
For me it is. It is still a bug, right?
Adding to readme recommended.

**Comment by leider** [comment]
and there still is the other one #55. - I can workaround that by using template string

**Comment by Shinigami92** [comment]
Closing as predecessor of #58
