### ISSUE TITLE
vue-prettier removes completely valid backslash escaping character if it is occuring in text node after some text

### ISSUE THREAD

**Issue by seletskiy** [prettier/plugin-pug#59]
`@prettier/plugin-pug` version: 1.1.2

This is live recording of an editor which triggers prettier on each save.
As you can see there, every time I save a file one backslash is disappearing after another.

![vue-prettier bug](https://user-images.githubusercontent.com/674812/72098302-45750d80-332f-11ea-91b9-172d4d56ccbd.gif)

I also want to mention, that:

* will cause to `\` to disappear on formatting:
  ```
  h2 ID \#{{ id }}
  ```

* will **not** cause `\` to disappear:
  ```
  h2 \#{{ id }}
  ```

So, the problem is somehow linked to the text which precedes `\`.

Escaping is described here: https://pugjs.org/language/interpolation.html#string-interpolation-escaped

**Comment by Shinigami92** [comment]
I think I will fix this bug within the next 2 days

**Comment by seletskiy** [comment]
@Shinigami92: thanks!

**Comment by seletskiy** [comment]
As a workaround I use `#{'#{{ id }}'}` for now. Ugly, but works.

**Comment by Shinigami92** [comment]
Released as [v1.1.3](https://www.npmjs.com/package/@prettier/plugin-pug/v/1.1.3)
Hopefully I didn't break pipeless text interpolation 🙏

Thanks for using my plugin 🙂

**Comment by seletskiy** [comment]
@Shinigami92: nice one, thanks! I can confirm that it works.

Here is :cake: for doing it TDD style :slightly_smiling_face:
