### ISSUE TITLE
Bug: Incorrect template inheritance processing 

### ISSUE THREAD

**Issue by anttibull** [prettier/plugin-pug#65]
This code should not change: 

 **Before**:
``` 
extends layout

block append head
```
**After**:
```
extends layout

block appendhead
```

As a result, such code does not work correctly

**Comment by Shinigami92** [comment]
Unfortunately I can not reproduce it 🙁 
Are you using the latest version?
You may need to provide further details.

**Comment by anttibull** [comment]
I did not have the latest version, I apologize. In the latest version, everything works well. Thank you for your work.
