### ISSUE TITLE
Parser Error: Missing expected } at the end of the expression

### ISSUE THREAD

**Issue by valera33** [prettier/plugin-pug#67]
When we use:
prettier: 1.19.1
@prettier/plugin-pug: 1.1.5

if PUG is something like:
```
.foo([myAttribute]="{param:'hello {name}' | translate:{'name':arg}}")
```
then we get such Error:

foo.pug[error] foo.pug: SyntaxError: Missing expected } at the end of the expression [{{{param:'hello {name}' | translate:{'name':arg}}}}] in angular-estree-parser
[error]     at o (/myProject/node_modules/prettier/parser-angular.js:15:16477)
[error]     at t.parseNgInterpolation (/myProject/node_modules/prettier/parser-angular.js:15:17607)
[error]     at n (/myProject/node_modules/prettier/parser-angular.js:15:28488)
[error]     at Object.t.parseInterpolation (/myProject/node_modules/prettier/parser-angular.js:15:28826)
[error]     at /myProject/node_modules/prettier/parser-angular.js:15:29569
[error]     at Object.parse (/myProject/node_modules/prettier/parser-angular.js:15:29226)
[error]     at Object.parse (/myProject/node_modules/prettier/index.js:9739:19)
[error]     at coreFormat (/myProject/node_modules/prettier/index.js:13252:23)
[error]     at format (/myProject/node_modules/prettier/index.js:13510:73)
[error]     at formatWithCursor (/myProject/node_modules/prettier/index.js:13526:12)

**Comment by Shinigami92** [comment]
Will target this bug upcoming weekend

**Comment by valera33** [comment]
thank for the very quick fix! it is ok now!
