### ISSUE TITLE
wrong new line in attributes

### ISSUE THREAD

**Issue by valera33** [prettier/plugin-pug#68]
When we use:
prettier: 1.19.1
@prettier/plugin-pug: 1.1.5

if PUG is something like:
```
.foo(*ngIf="myObjectAsync | async as myObject; else fallbackTemplate")
```

then we get such result:
```
.foo(*ngIf="myObjectAsync | async as myObject;
else fallbackTemplate")
```
It shouldnt add any line breaks here, or if it does then it should add "\\" at the end of first line.

**Comment by Shinigami92** [comment]
I think I can merge this with #67

**Comment by valera33** [comment]
thank for the very quick fix! it is ok now!
