### ISSUE TITLE
Moving to @prettier/plugin-pug

### ISSUE THREAD

**Issue by Shinigami92** [prettier/plugin-pug#7]
@prettier @lipis

Referring to https://github.com/prettier/prettier/issues/6245#issuecomment-506885029 and https://twitter.com/PrettierCode/status/1144730688727523328

Generally, I would support it if we move the repository to [@prettier/plugin-pug](https://www.npmjs.com/package/@prettier/plugin-pug) and [prettier/plugin-pug](https://github.com/prettier/plugin-pug)

But I have some questions:
- Maintainer of the repo
  It would be very nice if I can stay as the repo maintainer
- WebHooks
  I have currently setup a WebHook linked to my private Discord Server to be notified about everything
  Can I have this also in the new repo?
- Publishing in scope of @prettier to npm
  How can **I** publish a new version of the plugin in the scope of prettier?
- Transferring current issues
  Would be nice if also closed issue could be transferred
- Azure Pipelines
  How can I maintain the Azure build pipeline?
  Also I want to setup junit reporter in near future

**Comment by j-f1** [comment]
I’ve sent you an invite to the Prettier org. You should be able to transfer this repo into the Pug team I’ve created for you. The webhooks, issues, and Azure Pipelines setup should transfer. If you don’t end up with admin privileges for the repo, message me here and I’ll get that set up. Unfortunately, I can’t add you to the npm scope since I’m not a member of that scope — cc @azz @suchipi

**Comment by Shinigami92** [comment]
<img width="1388" alt="Bildschirmfoto 2019-07-02 um 19 50 29" src="https://user-images.githubusercontent.com/7195563/60534713-b7c2c080-9d02-11e9-8a64-21dc44ace1df.png">

**Comment by Shinigami92** [comment]
Ok, I have no access to the settings at the moment.
Can you give me the permissions?

**Comment by Shinigami92** [comment]
@j-f1 Maybe the problem is that I'm not a maintainer in https://github.com/orgs/prettier/teams/pug/members

**Comment by lipis** [comment]
You should have full access right now! Welcome on board.

**Comment by Shinigami92** [comment]
Ok
- Azure Pipelines re-setup is working.
- Discord WebHook is working.

Last step: I need to be in the https://www.npmjs.com/org/prettier orga in npm to release a new version
My npm User is: https://www.npmjs.com/~shinigami92

**Comment by Shinigami92** [comment]
I was notified by discord that you @j-f1 have added a new collaborator (me)
After this change I cant access the hole settings anymore

![image](https://user-images.githubusercontent.com/7195563/60547004-ebabdf00-9d1e-11e9-9798-c41db8b849aa.png)

![image](https://user-images.githubusercontent.com/7195563/60547032-f797a100-9d1e-11e9-97ab-251fbfc0ea12.png)

**Comment by lipis** [comment]
I made you an admin.. _with great power comes great responsibility..._ Use it with care :)

**Comment by Shinigami92** [comment]
Thank you @lipis, I will take care and I am a truthful person.

**Comment by j-f1** [comment]
Sorry about that! I changed the team settings to only have access to some of the settings so future collaborators couldn’t mess things up, then added you as an admin so you could access all of the settings. Something must’ve not gotten saved in the process.

**Comment by azz** [comment]
@Shinigami92 sent you an invite to the npm org. Once you've accepted you should be able to publish `@prettier/plugin-pug`. If not give me a shout and I'll sort out the permissions (npm is a bit annoying, you can't define teams/packages before invites are accepted or packages are published).

Once the package is published I can correctly set up the `pug` team on the `@prettier` org.

**Comment by Shinigami92** [comment]
I have accepted the invitation. 
Also want to let you know that I have 2FA or MFA setup for everything :)

It is currently ~6:00 in the morning (in germany) and I'm waking up slowly ^^'
Will publish a version (or maybe also all versions from the past :thinking:?) later in the day when I'm sure I'm not tired and dont make any mistakes ^^

**Comment by Shinigami92** [comment]
I published each version and used following steps:

```md
-- Repeat (replace X with 1..8)
git checkout 1.0.0-alpha.X
rm -Rf node_modules && rm yarn.lock && rm -Rf dist
-- Update packag.json
yarn
yarn build
yarn test --silent
npm publish --dry-run
npm publish --access public --tag alpha

-- Last Step
npm dist-tag add @prettier/plugin-pug@1.0.0-alpha.8 latest
```

Maybe I will release an  alpha.9 in short time without code changes but link/readme changes only so it correctly reflected on npmjs.com.

I also added a thanks to the readme for your help.

If you want, you can now twitter 😜

Will close this issue now 🎉
