### ISSUE TITLE
Bug: class formatting introduces trailing parenthesis if class length is greater than prettier's printWidth setting

### ISSUE THREAD

**Issue by fiznool** [prettier/plugin-pug#73]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.1.7        |
| Prettier | v1.19.1       |
| Node     | v13.6.0       |
| OS       | win,linux,mac |

## Input

- With prettier's default setting of `printWidth: 80`

```pug
div(class="bg-red-10 border-l-2 border-red-600 text-red-700 mb-4 rounded-r-10 font-normal")
```

## Output or Error

```pug
.bg-red-10.border-l-2.border-red-600.text-red-700.mb-4.rounded-r-10.font-normal(
)
```

## Expected Output

```pug
.bg-red-10.border-l-2.border-red-600.text-red-700.mb-4.rounded-r-10.font-normal
```

## Additional Context

Note the extra parens at the end of the actual output. These only appear if the input class length is > prettier's printWidth setting.

**Comment by Shinigami92** [comment]
Seems like just one formatting would give this result ...
So if you do the formatting twice, it will solve itself

https://github.com/prettier/plugin-pug#prettier-options
That's what I mean by `Currently not very accurate, but works`

**Comment by Shinigami92** [comment]
Note to me:

https://github.com/prettier/plugin-pug/blob/1f201f62b98a74901cbfbbad087a8318c82a49a0/src/printer.ts#L260

In this line the class attribute length (`tempToken.name.length` = `5`) is added for each css class 😒

**Comment by Shinigami92** [comment]
Good news, I've fixed it
But I also want to fix some other bugs and bundle a release of all fixes instead of releasing a small change every day ^^
I hope it's okay for you to wait a few days

**Comment by fiznool** [comment]
Great thanks! No big deal waiting, it’s not a showstopper issue 👍
