### ISSUE TITLE
Bug: doent respect printWidth of configuration (border values)

### ISSUE THREAD

**Issue by valera33** [prettier/plugin-pug#76]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.1.8        |
| Prettier | v1.19.1       |
| Node     | v13.6.0       |
| OS       | linux |

## Input

```pug
.baz
  .baz(foo="Lorem Ipsum is simply dummy text of the printing and typesetting industry.", bar="Lorem Ipsum is simply dum")
```
Long line is 122 characters long.

## Output

```bash
.baz
  .baz(foo="Lorem Ipsum is simply dummy text of the printing and typesetting industry.", bar="Lorem Ipsum is simply dum")
```
Output is the same as input, which is wrong

## Expected Output

```pug
.baz
  .baz(
    foo="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    bar="Lorem Ipsum is simply dum"
  )
```

## Configuration

```javascript
'use strict';
module.exports = {
  printWidth: 120,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: false,
  trailingComma: 'es5',
  bracketSpacing: true,
  arrowParens: 'avoid',
};
```
`printWidth` is configured to 120, but if a line is 121 or 122 characters long, it doesn't add a new line but it should. If line is 123 characters long it is working as expected.

**Comment by Shinigami92** [comment]
Thx for the report, will fix it when I have little bit more time

**Comment by Shinigami92** [comment]
🤯 https://github.com/prettier/plugin-pug/commit/0ffe395feaa673cb1ae90bce958d9ff47cc27713

**Comment by valera33** [comment]
thx for the fix, didn't have time to check it earlier, works as expected now!
