### ISSUE TITLE
Bug: A semicolon is inserted before the interpolation, starting with the template literal

### ISSUE THREAD

**Issue by yuheiy** [prettier/plugin-pug#85]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.3.0        |
| Prettier | v2.0.5       |
| Node     | v12.16.3       |
| OS       | mac |

## Input

```pug
= ``
```

## Output or Error

```bash
= ;``
```

## Expected Output

```pug
= ``
```

## Additional Context

A semicolon will not be inserted if there is a string or something before the template literal.

```pug
= value + ``
= '' + ``
```

**Comment by Shinigami92** [comment]
Can you also give me your `.prettierrc.json` configuration?

**Comment by yuheiy** [comment]
I'm using the default configuration.

**Comment by Shinigami92** [comment]
Ok, please be patient with me
I have to start regular work and hopefully I can fix this in the evening (~ 8-9h).
