### ISSUE TITLE
Bug: Blank lines in multi-line comments are indented

### ISSUE THREAD

**Issue by yuheiy** [prettier/plugin-pug#89]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.4.0        |
| Prettier | v2.0.5       |
| Node     | v12.17.0       |
| OS       | mac |

## Input

```pug
//-
  a

  b
```

## Output

```pug
//-
  a
  
  b
```

White spaces are inserted at the beginning of the 3rd line.

## Expected Output

```pug
//-
  a

  b
```

## Additional Context

The same is true if the comments are written from the first line.

input:

```pug
//- a

  b
```

output:

```pug
//- a
  
  b
```

White spaces are inserted at the beginning of the 2nd line.

This is probably related to #90 #91 and #92.

**Comment by Shinigami92** [comment]
Ok, identified the problem

I'm processing a token stream and there is a `val` after a `newline` that contains an empty string

![image](https://user-images.githubusercontent.com/7195563/82989969-bcb7ef00-9ffb-11ea-85ef-829d461d217d.png)

So I need to implement a check to find out if the next token is a `text` token and contains a (trimmed) empty string

**Comment by Shinigami92** [comment]
Ok sorry, need to switch to work right now

The fix it not that easy, because it's related to pipeless text syntax

```pug
p.
  some text
  some more text <!-- This would fail with my current approach -->
```

https://pugjs.org/language/plain-text.html

**Comment by Shinigami92** [comment]
Mh 🤔 
I have managed the blank lines
But I found out that my `printWidth` doesn't work well with set to `3` anymore 🤨

Also I'm feeling not very safe enough with my current tests in `test/issues/issue-89`

Do you have some more test-cases with very have edge cases?

**Comment by Shinigami92** [comment]
Update: I checked my changes agains some private code on my mac
It doesn't broke anything that is currently working

So I feel a little bit more safe now, but well wait a little bit more on your response, whether you have some more edge cases

**Comment by yuheiy** [comment]
Sorry, I don't have more edgy cases.
