### ISSUE TITLE
Bug: Apostrophes are destroyed inside of angulars interpolation 

### ISSUE THREAD

**Issue by Ulrikop** [prettier/plugin-pug#9]
**Used configuration:**
```json
{
  "printWidth": 120,
  "tabWidth": 2,
  "useTabs": false,
  "singleQuote": false,
  "bracketSpacing": true
}
```

**Input file:**
```pug
.without-apostrophe(foo="{{'hello world' | uppercase}}")
  | {{'hello world' | uppercase}}

.with-apostrophe(foo="{{'it\'s me' | uppercase}}")
  | {{"it's me" | uppercase}}
```

**Output file:**
```pug
.without-apostrophe(foo="{{'hello world' | uppercase}}")
  | {{'hello world' | uppercase}}

.with-apostrophe(foo="{{'it's me' | uppercase}}")
  | {{ 'it"s me' | uppercase }}
```

**Expected behavior:**
It should not change a text which will be displayed (_it's me_ was changed to _it"s me_).

Additional the handling of spaces after `{{` and before `}}` should be consistently. The added spaces at the second `{{ ... }}` is the expected behavior.

**Comment by Shinigami92** [comment]
I fixed it in attributes, but I did not find a way to handle that in text 🤔 

The thing is that the correct format needs to be
```pug
.with-apostrophe(foo="{{ 'it\'s me' | uppercase }}")
```
and not
```pug
.with-apostrophe(foo='{{ "it's me" | uppercase }}')
                            ~ The end of the string reached with no closing bracket ) found
```

Therefore, we cant quote the text in a way without to escape the single quote
_Needs this_
```pug
.with-apostrophe(foo='{{ "it\'s me" | uppercase }}')
```

So I have written code to procude
```pug
.with-apostrophe(foo="{{ 'it\'s me' | uppercase }}")
```
and it is working.
BUT it brokes another test ☹
```diff
// Quotes › should format single to double quotes
// and
// Quotes › should use double quotes by default

- Expected
+ Received

- .grey--text {{ $t('my-language-key.title') }}
+ .grey--text {{ $t("my-language-key.title") }}
```
I don't know how to pass them

Hope someone can help me here: https://github.com/prettier/plugin-pug/blob/0817c64/src/index.ts#L391-L407

**Comment by Shinigami92** [comment]
@j-f1 Do you know if we have any regex/JS experts in @prettier/core who can help me here?

**Comment by azz** [comment]
@lydell!

**Comment by lydell** [comment]
Hehe, yeah, I like regexp, but I'm not quite sure what you are trying to do here? People write Angular using Pug and therefore embed pieces of Angular template code inside attributes, and you're trying to do regex replacements on them (instead of parsing)?

**Comment by Shinigami92** [comment]
@lydell Yea... something like that. One problem is that I cant use prettier to format _js_ code in example mustache brackets because the prettier will use linebreaks and semicolons and stuff and breaks the formatting completely.

Therefore I want to handle quotes on this place:
https://github.com/prettier/plugin-pug/blob/8890d4c957d4392c03034800086ed387bcc4aca4/src/index.ts#L401-L410

But it has sideeffects and breaks my other tests in `./test/quotes/**`
https://github.com/prettier/plugin-pug/blob/8890d4c957d4392c03034800086ed387bcc4aca4/test/quotes/single-to-double/formatted.pug#L4

formats to:
```pug
.grey--text {{ $t("my-language-key.title") }}
//                ~                     ~
```

and I don't know why 🤔 

See also [Build-62](https://dev.azure.com/shinigami92/Prettier%20Pug%20plugin/_build/results?buildId=62) and click on **Test**

**Comment by lydell** [comment]
It's not possible to do this safely with regex. Consider this example:

```js
`"${ `Jean ${ '"John"' } d'Arc`.toUpperCase() }"`
```

**Comment by Shinigami92** [comment]
Besides this example hurts my brain, do you know another strategy?


I will build a test for you example 😁

**Comment by lydell** [comment]
I think you'll have to parse it as JS and then print is somehow. If it _is_ JS. But btw, how can you know that the attribute contains Angular code?

**Comment by Shinigami92** [comment]
If text starts and ends with mustache brackets, I assume js code.
I cant use prettier format js because that produce newlines. I need everything in a single line. 

Maybe I should check if there are different quotes in the string and if so then dont touch it?

**Comment by ikatyang** [comment]
FYI, there is a [`__ng_interpolation`](https://github.com/prettier/prettier/blob/91a7aa081e344a830e33a982856674757d73f701/src/language-js/parser-angular.js#L27) parser, which is used for this purpose.

**Comment by Shinigami92** [comment]
@ikatyang Thank you, you have definitely put me on the right track!
I didn't used [`__ng_interpolation`](https://github.com/prettier/prettier/blob/91a7aa081e344a830e33a982856674757d73f701/src/language-js/parser-angular.js#L27) directly, but I tried `format` with different parsers.

At first I tested `format(code, { parser: 'angular' })`.
That solves already some problems like whitespaces, but didn't produces the final wanted result.
It doesn't change quotes.

So I tried `format(code, { parser: 'vue' })`... same as `'angular'` ^^

Then I tried `format(code)`, so no parser at all? No it takes `'babel'` and prints a warning in console...
**BUT** it produces greate results 🎉

I needed to remove the last `:` semi-colon and also the `eof`. And I needed to use an internal `printWidth` of a large number so it don't wraps... Over 9000 😁 seams legit...

I think I can merge this to release a next alpha, but keep in mind that it will break code that uses more then one statement in a text. But in my opinion, something like this should be done on the `Controller`/`Component` side.

**Comment by j-f1** [comment]
Why didn’t you want to use the `__ng_interpolation` parser?

**Comment by Shinigami92** [comment]
Um ... I thought it's used internally
Besides, it works just fine at the moment

And I do not really know how to import the function `__ng_interpolation` into my TypeScript code

**Comment by j-f1** [comment]
You should be able to specify `parse: '__ng_interpolation'` in your call to `format()`.

**Comment by Shinigami92** [comment]
Ohhhhhh, this think IS the parser .-.
💡 

![Mind Blow](https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif)

**Comment by Shinigami92** [comment]
Ah, sadly it throws an error:
```SyntaxError: Unexpected token Lexer Error: Unexpected character [`]```

```ts
code = format(code, { parser: '__ng_interpolation' as any, singleQuote: !singleQuote, printWidth: 9000 });
```

So nevermind 🤷‍♂️

**Comment by j-f1** [comment]
What’s in the `code` variable when the error is thrown?

**Comment by Shinigami92** [comment]
```ts
`"${ `Jean ${ '"John"' } d'Arc`.toUpperCase() }"`
```

**Comment by j-f1** [comment]
I think you’re supposed to pass in the whole interpolation, i.e. `{{ `"${ `Jean ${ '"John"' } d'Arc`.toUpperCase() }"` }}`.

**Comment by Shinigami92** [comment]
No it's not working 😕

```ts
code = format(
  `{{ ${`"${`Jean ${'"John"'} d'Arc`.toUpperCase()}"`} }}`,
  {
    parser: '__ng_interpolation' as any,
    singleQuote: !singleQuote,
    printWidth: 9000
  }
);
```

```shell
SyntaxError: Unexpected token {, expected identifier, keyword, or string

      at o (node_modules/prettier/parser-angular.js:1:43202)
      at t.parseNgInterpolation (node_modules/prettier/parser-angular.js:1:44326)
      at n (node_modules/prettier/parser-angular.js:1:54823)
      at Object.t.parseInterpolation (node_modules/prettier/parser-angular.js:1:55161)
      at node_modules/prettier/parser-angular.js:1:55798
      at Object.parse (node_modules/prettier/parser-angular.js:1:55454)
      at Object.parse$2 [as parse] (node_modules/prettier/index.js:10629:19)
      at coreFormat (node_modules/prettier/index.js:13888:23)
      at format (node_modules/prettier/index.js:14146:73)
      at formatWithCursor (node_modules/prettier/index.js:14162:12)
```

**Comment by j-f1** [comment]
It looks like the Angular parser doesn’t support template strings :(

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUADAFnAGwImwEoACEAGhAgAcYBLaAZ2VAEMAnLiAdwAK3BGxQcAbhEYATaiABGXDmADWcGAGU6yxlADmyGFwCucGrhgBbAgHVcjeC21g4GkQ8biHAT2TgWbDS6LHBcMAJKepYcyKgcBCE0AFYsAB4AQkqq6hoclnAAMrpwsfGJICmpGrp6BHAAisYQ8KUJZiDaXCFcfgD6vfq9uvBcdBAEHEzQcnRcwzYyMLjIABwADDSzECE2SnR+s3Dd4iU0AI5N8BH0oiAcLAC0UHBw0q9yXHAXjJ8RHFExJBxNo0EKWRiGEztFg1OqNZolIFldowDjyBbSJbIABMNCMHEYBBqAGEIJZon4oNBTiBjCEACpo0TAkIAX1ZQA)
```sh
--parser __ng_interpolation
```

**Input:**
```js
foo(`hello`) 
```

**Output:**
```__ng_interpolation
o@https://prettier.io/lib/parser-angular.js:1:43190
parseNgInterpolation@https://prettier.io/lib/parser-angular.js:1:44300
n@https://prettier.io/lib/parser-angular.js:1:54797
parse@https://prettier.io/lib/parser-angular.js:1:55428
parse$2@https://prettier.io/lib/standalone.js:12947:24
coreFormat@https://prettier.io/lib/standalone.js:16216:28
format@https://prettier.io/lib/standalone.js:16476:83
format@https://prettier.io/lib/standalone.js:31000:28
formatCode@https://prettier.io/worker.js:234:27
handleMessage@https://prettier.io/worker.js:185:28
onmessage@https://prettier.io/worker.js:155:27
```

**Comment by Shinigami92** [comment]
Yea, checked it at [stackblitz.com](stackblitz.com).
Angular doesn't support template strings in `html` 😌
But Vue does!

**Comment by ikatyang** [comment]
Their grammars are different, you should use [`__vue_expression`](https://github.com/prettier/prettier/blob/91a7aa081e344a830e33a982856674757d73f701/src/language-js/parser-babylon.js#L204) if you'd like to parse vue's `{{expression}}`.

**Comment by Shinigami92** [comment]
@ikatyang Nice to know that there are so many internal things I didn't noticed ^^'
I only see the typescript `.d.ts` definitions and use them as docu and learn how to use prettier

So I will try that.
But it seams that `__vue_expression` use the `babel`-parser.

I also don't know how to assume whether it is using vue or angular.
I could introduce an option for `framework`, but I think that is not really smart 😕

Do you have an example for testing? So a vue and an anguar snippet that are formatted differently?

**Comment by ikatyang** [comment]
> But it seams that `__vue_expression` use the `babel`-parser.

More precisely, the babel _expression_ parser. Though they use the same parser, their `|`s are printed differently, `|` is printed as a filter in vue but a bitwise OR in js.

> I also don't know how to assume whether it is using vue or angular.
> I could introduce an option for `framework`, but I think that is not really smart 😕
> Do you have an example for testing? So a vue and an anguar snippet that are formatted differently?

IIRC, they are formatted in the same way, the only difference between them is that they support different grammars. I guess you could try to guess which parser to use based on attribute names next to it (vue: `v-*`, `:*`, `@*`, etc.; angular: `[*]`, `(*)`, `[(*)]`, etc.), and try another parser if the parsing failed, just like [what `typescript` parser did](https://github.com/prettier/prettier/blob/8b039ae195d95a780152b21a36acbfaf2d564693/src/language-js/parser-typescript.js#L10-L18).

**Comment by Shinigami92** [comment]
Uh... That would work for attributes. But currently I'm working on `text`,  
so there is no attribute key like `v-*` and so on.

I only have something like:

```pug
span {{ my.angular.value }} {{ someInputFromComponent | uppercase }}
```

**Comment by ikatyang** [comment]
You can simply choose either parser to use, and use another one if the previous parsing failed. The attribute names are just hints for better guessing, it does not really matter if it's wrong since one of the two parsers must be the correct one and their formatting results are the same.
