### ISSUE TITLE
Bug: Reordering of classes/ids ignores "hidden" DIVs

### ISSUE THREAD

**Issue by david2tm** [prettier/plugin-pug#95]
## Info
Input, output, expected will explain it a lot better.

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.2.0        |
| Prettier | v1.19.1       |
| OS       | mac |

## Input

```pug
        fieldset
          .test1
            .test2
              .test3
                .test4#my-subtle-id test text
```

## Output

```pug
        fieldset#my-subtle-id
          .test1
            .test2
              .test3
                .test4 test text
```

## Expected Output

```pug
        fieldset
          .test1
            .test2
              .test3
                #my-subtle-id.test4 test text
```

**Comment by Shinigami92** [comment]
But using `#my-subtle-id.test4` directly is working, is it?
So this is not a huge bug with no workaround.
Will try to fix it when I have a bit more time.

If you want to fix it on your own, feel free to open a PR and I will review it 🙂

**Comment by david2tm** [comment]
Yes using `#my-subtle-id.test4` is working.
