### ISSUE TITLE
Option to not format double curly braces (mustache)?

### ISSUE THREAD

**Issue by xerroxcopy** [prettier/plugin-pug#98]
## Request / Idea

I'm using [Stein](https://steinhq.com/) for a very simple website together with pug. Stein [Expedite](https://docs.steinhq.com/expedite-display-data) allows users to use column-names directly in HTML, as in `{{colname}}`. However, prettier seems to format this into `{{ colname }}` even when `bracketSpacing` is set to false. And Stein does not work if formatted that way. Is this possible, or am I doing something wrong / missing something?
My `.prettierrc.js` looks like below:

```js
module.exports = {
  singleQuote: true,
  semi: false,
  overrides: [
    {
      files: '*.pug',
      options: {
        parser: 'pug',
        bracketSpacing: false, // for stein expedite
      },
    },
  ],
}
```

## Input

```pug
div(
  data-stein-url='https://api.steinhq.com/v1/storages/[spreadsheet]/[sheet-name]',
  data-stein-limit='100'
) 
  div {{date}}

```

## Expected Output

exactly the same as input.

**Comment by Shinigami92** [comment]
Maybe I will try to fix this this weekend, but don't know I have time
But currently there is a audit vulnerability in lodash that is blocking my CI

**Comment by Shinigami92** [comment]
@xerroxcopy Can you give me more examples for testing purposes?

IMO it should be more then just text-tokens 🤔

**Comment by xerroxcopy** [comment]
Sorry for the late response. As far as Svelte goes, text should be enough. Not sure of other possible examples though...

**Comment by Shinigami92** [comment]
> Sorry for the late response. As far as Svelte goes, text should be enough. Not sure of other possible examples though...

Oh interesting info that you are using Svelte
I'll add a new label for this framework

**Comment by Shinigami92** [comment]
I will now release a version `1.5.0`
Thank you for being in the pug community and using my plugin 🎉

**Comment by xerroxcopy** [comment]
Thank you so much, i've just updated it and it works perfectly! and i'm sorry i meant stein, not svelte... my bad.
