### ISSUE TITLE
Bug: incorrect quotation change in attribute using concatenation with variable

### ISSUE THREAD

**Issue by seletskiy** [prettier/plugin-pug#99]
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.4.4        |
| Prettier | v2.0.5       |
| Node     | v14.2.0       |
| OS       | linux |

## Input

1. Single quoted strings concatenation
    ```pug
    script(async, src='http://localhost:' + port + '/livereload.js')
    ```

2. Double quoted strings concatenation
    ```pug
    script(async, src="http://localhost:" + port + "/livereload.js")
    ```

## Output or Error

1. First and last quote replaced with `"`, while middle stays `'`
    ```bash
    script(async, src="http://localhost:' + port + '/livereload.js")
    ```

2. Middle quotes are escaped
    ```pug
    script(async, src="http://localhost:\" + port + \"/livereload.js")
    ```

## Expected Output

```pug
script(async, src='http://localhost:' + port + '/livereload.js')
```

## Additional Context

Syntax described at https://pugjs.org/language/attributes.html#attribute-interpolation (scroll past Caution section).

Workaround:

```pug
script(async, src=`http://localhost:${port}/livereload.js`)
```

**Comment by Shinigami92** [comment]
This is already known and you should use the workaround documented in the README.md for this
https://github.com/prettier/plugin-pug#some-workarounds

**Comment by Shinigami92** [comment]
duplicate #58
